### PR TITLE
Add events for network connections

### PR DESCRIPTION
**Pull request by killjoy1221**
Adds events for LOGIN, JOIN, LEAVE on client and server.

Usage:
```java
S2CPlayConnectCallback.EVENT.register((connection, packetListener) -> {
     // joined on client
    ClientPlayNetworkHandler handler = (ClientPlayNetworkHandler) packetListener;
 });
C2SPlayConnectCallback.EVENT.register((connection, packetListener) -> {
    // joined on server
    ServerPlayNetworkHandler handler = (ServerPlayNetworkHandler) packetListener;
});
```

### CODE REVIEW

**Comment by grondag** [comment]
Do generic events have a benefit beyond avoiding `@SuppressWarnings({ "rawtypes", "unchecked" })`?

**Comment by grondag** [comment]
Overall generics don't seem worth the additional complexity and maintenance burden.

`ConnectionEvents.getListenerClass()` is problematic.  If the event only supports a fixed set of PacketListener subtypes, then why not implement type-specific events?  (Which would also seem to mitigate the need for generics.). Is it useful and necessary to support all of those listener types?

Lastly, it would be helpful in the PR description to elaborate on some of the specific expected use cases for these events.  They should have reasonably broad utility to be included in the Fabric API.

**Comment by killjoy1221** [comment]
The generic events have been removed. I've also limited how the events work and when they are fired.

**Comment by grondag** [comment]
This is coming along and I appreciate the simplifcations.

Would it be even simpler to have a distinctly typed instance for each packet listener type?  Events are cheap to create.  You'd need no hash map then, and you could offer strongly-typed packet listener access within each event.  There may well be a good reason not to do it that way, but it isn't obvious to me.  In that case, please help me understand.  

If you could also update the PR header to bring it up to date with the current approach and describe some intended use cases, that would make it easier to get more feedback on  it.

**Comment by killjoy1221** [comment]
All the events are working now, but I'm wondering if I should implement them by using the channel pipeline instead.

**Comment by grondag** [comment]
> ... I'm wondering if I should implement them by using the channel pipeline instead.

Would the intent be to avoid the ```instanceof``` checks?  Those seem reasonable to me as-is, and I didn't spot an easy way to avoid them in those cases.  The PR is already slimmed down nicely so if the result is more complexity or unless it somehow avoids a performance concern (seems unlikely given the relative infrequency of these events) I'd say not worth. 

I don't have any big concerns about the code now, but would like to see some other feedback on it.  In particular, I'd like to know if the community thinks all of these events will be generally useful or just some of them.

For example, is there much difference in utility between Leave/Login events?

**Comment by Pyrofab** [comment]
I would be in favour of merging server and client callbacks, as they are exactly the same except for the side they are fired on. Why not just pass a `NetworkSide` parameter instead ? I think every event should be as versatile as possible, within reason. 
Besides, `Server/Client` prefixing is slightly confusing, without reading the javadoc I do not know if `ServerJoinEvent` means it is fired on the server or it is fired when a client joins a server.

**Comment by Daomephsta** [comment]
In the Forge community, data syncing by mods can cause excessive join times. Since syncing data with clients would be a common usage of the JOIN event, I suggest we also investigate if it's possible to provide a highly efficient syncing framework to mitigate that issue in the Fabric community.

**Comment by Pyrofab** [comment]
For data syncing, there is also #262 to take into account. The Join event would probably best be used for player-specific data syncing, which is less likely to benefit from a framework.

**Comment by grondag** [comment]
> I would be in favour of merging server and client callbacks, as they are exactly the same except for the side they are fired on. Why not just pass a `NetworkSide` parameter instead ? I think every event should be as versatile as possible, within reason.

On an integrated server would this not cause event listeners to be called from both sides?

**Comment by grondag** [comment]
Regarding data synching, it's an interesting question.  Unless it would obviate the need for the current PR entirely I suggest we try to keep the initial scope as small as possible.  Can always add more stuff later.  It's harder to take stuff out.

**Comment by grondag** [comment]
> Besides, `Server/Client` prefixing is slightly confusing, without reading the javadoc I do not know if `ServerJoinEvent` means it is fired on the server or it is fired when a client joins a server.

Should we use the S2C C2S naming convention adopted elsewhere here also?  I know some in the community aren't fans of it, but I personally find it clear and it is at least consistent.

**Comment by Pyrofab** [comment]
> would this not cause event listeners to be called from both sides ?
Of course it would, that is why we would pass the NetworkSide parameter. Mods do sided checks all the time with `isClient`, so why not here ?

**Comment by sfPlayer1** [comment]
I don't think the actions are sufficiently directional for S2C/C2S, half of them are triggered through a local decision. What may be useful however is wrapping the events in two classes Client-/ServerNetworkStateChange or similar, reducing both the class count and making it more obvious which side is affected. Due to side isolation concerns I prefer this over passing an isClient/side parameter to the callbacks.

**Comment by grondag** [comment]
> Of course it would, that is why we would pass the NetworkSide parameter. Mods do sided checks all the time with `isClient`, so why not here ?

Events are inexpensive to create and should (IMO) be as specific and narrowly targeted as they can reasonably be, and ideally listeners that are registered to an event will always want the callback. If listeners have to do filtering in every use case, that suggests the event is too coarse.

It shouldn't actually matter for performance in this particular case, but it's a good principle to follow.  

I also don't know if there are any bad side effects if the event listener doesn't bother to check in that case that wouldn't be immediately obvious.  If so, it goes against the "hide the ejection seat lever" principle.

**Comment by killjoy1221** [comment]
>Should we use the S2C C2S naming convention adopted elsewhere here also? I know some in the community aren't fans of it, but I personally find it clear and it is at least consistent.

While useful for packets, the client will never touch the server events and vice versa. What I am doing is putting them in server client packages. The client shouldn't listen to the events in the server package. 

I actually named the events "backwards" on purpose. The event is for when the client logs into the server. If needed, I can name the event `LoginToServerOnClient` and `LoginFromClientOnServer`

**Comment by grondag** [comment]
I also like the idea of bundling the events into parent classes for the reasons stated.  I suggested the events should be distinct types, but they don't need to be in different files.

**Comment by grondag** [comment]
I don't have strong opinions on the names.  For that, you'll need @InsomniaKitten.

**Comment by asiekierka** [comment]
Join/Leave -> Client/Disconnect, and use S2C/C2S, IMO.

**Comment by sfPlayer1** [comment]
Sorry, I don't think this is ok if the issue mentioned earlier remains unaddressed, I assembled an alternative API below.

The events reflect state changes, the states are handshake, login, play and status. There is only ever one side that causes such a state change, applies it locally and propagates to the other. This also means that can be only either 2SLogin or S2CLogin, never both.

Additionally, there are really two distinct concepts: Network system state changes and actual connection activity. Mixing them is questionable.

I propose the following structure with two top level classes:
ClientNetworkCallback.{StateChange, Disconnect, Complete, Join, Leave}
ServerNetworkCallback.{StateChange, Disconnect, Complete, Join, Leave}

Low level events:
* StateChange.onChange(NetworkState state, ClientConnection connection, PacketListener listener)
-> Direct hook of ClientConnection.setPacketListener, access to the pre-GAME network activity
* Disconnect.onDisconnect(NetworkState state, ClientConnection connection, PacketListener listener)
-> Direct hook of ClientConnection.channelInactive, disconnect for any state

High level events:
* Complete.onComplete(*PlayerEntity player)
-> after switching to GAME, but before sending the game join packet, indicates the entire handshake is done
* Join.onJoin(*PlayerEntity player))
-> after sending/receiving the game join (or brand?) packet
* Leave.onLeave(*PlayerEntity player), TextComponent reason)
-> hooks start of *PlayNetworkHandler.onDisconnected - should always happen if onComplete happened

Join and Leave are the primarily useful ones. Client-/ServerPlayerEntity already expose ClientConnection and the packet listener.

**Comment by i509VCB** [comment]
I think these would make sense/is replaced with #455 since this seems to have been untouched for a few months. 

If this will be continued, it needs to be retargetted to 1.15 as release is coming soon.

**Comment by liach** [comment]
Note that these events' initial setup has been a bit troubled; the mixin in client connection may cause crash on dedicated server because of the absence of client network handlers

**Pull request closed without merging**
