### PR TITLE
Fix fabric-resource-loader not being bumped in #310

### PR DESCRIPTION
**Pull request by Prospector**
PR #310 should have bumped this but didn't

### CODE REVIEW

**Comment by modmuss50** [comment]
no, there are other modules that have this same problem.

#316 is working towards the full fix, I might have a look at a better version of 316 if I get a chance.

**Comment by Prospector** [comment]
Regardless, the version should've been bumped anyway. It just happens to be a fix to a big problem :P

**Comment by grondag** [comment]
Will this be needed if #323 is merged?

**Comment by modmuss50** [comment]
No, my PR removes the need for this

**Comment by Prospector** [comment]
Fixed in #298

**Pull request closed without merging**
