### PR TITLE
Allow specifying the render layer in FabricBlockSettings

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
Adds three methods to allow giving the block a different render layer

The testmod does not crash on a dedicated server
server480

### CODE REVIEW

**Review by modmuss50 — CHANGES_REQUESTED** [review]
Im not a fan of this, we (and in places vanilla) generally try to keep a good split between the client and server.

**Comment by frqnny** [comment]
I also agree, any client-only things should be done in the client mod initializer. Has this been tested in a dedicated server?

**Comment by BoogieMonster1O1** [comment]
> I also agree, any client-only things should be done in the client mod initializer. Has this been tested in a dedicated server?

i've tested it on a dedicated server. look at the image i posted

**Comment by BoogieMonster1O1** [comment]
probably not gonna get merged considering that people don't want it, so im just gonna close this one

**Pull request closed without merging**
