### PR TITLE
BiomeRegistry (Register biome by getting the next avaliable ID)

### PR DESCRIPTION
**Pull request by valoeghese**
If there are problems or better ways of doing things please let me know.

This does not add biomes to the world: it merely provides a way to register them.

### CODE REVIEW

**Comment by asiekierka** [comment]
Why doesn't just using Registry.register() without specifying a numeric ID work? The hasParent stuff is done automatically be the registry module.

**Comment by valoeghese** [comment]
Optimised code.

Also if the hasParent stuff is done automatically, then why does the private method in the `Biomes` class do it manually?

**Comment by asiekierka** [comment]
https://github.com/FabricMC/fabric/blob/master/src/main/java/net/fabricmc/fabric/impl/registry/BootstrapBiomeRegistryListener.java

Because so do we, but it's hidden away from the modder

**Comment by valoeghese** [comment]
Ok. If that part is already done by a registry listener I can just delete it. Easy Peasy :)

**Comment by asiekierka** [comment]
But then.. what does the PR bring over just using Registry.register directly?

**Comment by valoeghese** [comment]
True that... the only possible thing I can see is that you have 3 parameters instead of 2

**Comment by asiekierka** [comment]
Not really convincing, sorry...

**Comment by valoeghese** [comment]
if you use Registry.register

**Comment by valoeghese** [comment]
At least I now know how to optimise my code

**Pull request closed without merging**
