### PR TITLE
Update to loom 1.3 and use Mod Publish Plugin

### PR DESCRIPTION
**Pull request by modmuss50**
Update to Loom 1.3
Update to Gradle 8.2
Migrate to my [mod-publish-plugin](https://github.com/modmuss50/mod-publish-plugin)
Use sign jar task in dry run mode for all builds.

### CODE REVIEW

**Comment by mrjasonn** [comment]
@modmuss50 a suggestion would be making this update to Gradle 8.2 as well if possible.

**Comment by modmuss50** [comment]
@mrjasonn Yeah, I'm working on it. The curse publish plugin we use has some deprecation warnings in 8.2 so needs replacing first (We fail the build with deprecations).

**Comment by mrjasonn** [comment]
> @mrjasonn Yeah, I'm working on it. The curse publish plugin we use has some deprecation warnings in 8.2 so needs replacing first (We fail the build with deprecations).

Ok. I would also recommend you to have other people that are interested work with you on it so it gets done quicker. It would also be a good idea to make it so it can automatically update to a newer build of Loom 1.3 if possible and feasible.

**Comment by mrjasonn** [comment]
It would also be a good idea to do this for the other FabricMC projects.

**Comment by modmuss50** [comment]
I have already put quite a bit of effort into it here: https://github.com/modmuss50/mod-publish-plugin If you or anyone wishes to help out please let me know on discord, there is plenty to get on with!

I am going away for a few days shortly ✈️, I doubt ill be able to finish it before then so this PR might be blocked for a week or two.

**Comment by modmuss50** [comment]
Im going to merge this into the 1.20.2 branch, to test it out. Will then backport for the next 1.20.1 release 👍

**Pull request merged**
