### PR TITLE
[1.21.1] Add Passive, Neutral, Hostile, and Boss entity tags.

### PR DESCRIPTION
**Pull request by crispytwig**
Thought it was silly that these did not exist in Minecraft nor Fabric's tags, so I think it would be a good idea to create generators for them based on the tags I've added here. 

As @haykam821 pointed out, these will need to have the generators edited, but I'm not familiar with data generation, so I'll close this and leave it up to someone else to decide if they'd like to contribute this feature.

### CODE REVIEW

**Comment by crispytwig** [comment]
#c:bosses already exists, whoopsies

**Comment by TelepathicGrunt** [comment]
A mob can change its hostile status based on conditions. Like I have a monster that will attack players unless they wear bee armor, then the mob is neutral to the player. And so forth. 

I do not think tags is usable for this as behavior is dynamic. Not static like tags wants

**Comment by haykam821** [comment]
A mob that attacks based on armor would be neutral. For example, piglins are considered neutral.

**Review by haykam821 — CHANGES_REQUESTED** [review]
From a technical standpoint, this pull request is incorrect; it modifies the generated directory directly.

Instead, the data generators should be updated and ran to produce the files currently included in this pull request. Fields should also be added to `ConventionalEntityTypeTags` so that mods can reference these tags without constructing their own tag keys.

**Pull request closed without merging**
