### PR TITLE
Make FabricToolTags not deprecated

### PR DESCRIPTION
**Pull request by MrIbby**

### CODE REVIEW

**Comment by modmuss50** [comment]
Im not sure why this is Deprecated? was it a mistake, might be best to wait for asie to confirm that it was a mistake.

**Comment by Prospector** [comment]
it's gotta be a mistake. It was added as deprecated in the same commit that deprecated the old one.

**Comment by InsomniaKitten** [comment]
> Last Monday at 20:07 BST
> \<asie> no, i don't actually know which approach to stick to

**Comment by Prospector** [comment]
My vote is for FabricToolTags because it's in the mining levels class, hence tools.

**Comment by Prospector** [comment]
Oh, there's #188

**Pull request merged**
