### PR TITLE
Backported Fabric Fluid Api V1 to 1.16.

### PR DESCRIPTION
**Pull request by ghost**
This pull request backports the fluid api module #1784 to Minecraft 1.16.
For every info about this, checkout #1784.

## Additions

* `FabricFlowableFluid` class that extends `FlowableFluid`, implementing some common fluid customizations, and adding new customizations, such as fog, particles, sounds, viscosity, events...
* `FabricFluidTags` class that adds new tags for fluid customizations.
* `FabricFluidBlock` class that extends `FluidBlock`, adding a public constructor, so you don't need anymore to create a new class.

## Extra

* `FluidUtils` class that contains some utilities for fluids.
* `FabricFluidEntity` interface that implements some fluid-related entity features.
* `FabricFluidClientPlayerEntity` interface that implements some fluid-related client-side player entity features.
* `SoundParameters` class that incapsulates some sound parameters.
* `UnderfluidSoundLoop` class that implements a sound loop player used when the player is submerged by a fluid.

### CODE REVIEW

**Comment by Technici4n** [comment]
This is not forge, if the backport is straightforward it's better to leave it to the maintainers so that we don't have to track two PRs at the same time.

**Comment by frqnny** [comment]
imo porting should be okay, as long as the initial PR is merged. but for now port prs should remain stale under the main one is merged

**Comment by modmuss50** [comment]
I agree, no need to close this as its great work, but it will be easier for you to maintain one PR over 3. Then when the PR is ready to merge back/forward porting can be thought of, no need to waste time now.

Thanks, I will need to find some time to sit down and review the main PR 👍

**Comment by ghost** [comment]
There are some changes about the fog configuration, and is needed a mixin for the bucket filling sound.

**Comment by ghost** [comment]
Closed: See the reason here: https://github.com/FabricMC/fabric/pull/1784#issuecomment-988169299

**Pull request closed without merging**
