### PR TITLE
Add more metadata to modules and Mod Menu support

### PR DESCRIPTION
**Pull request by Prospector**
~~Still to figure out: icons.~~

~~Should I put the same icon in every module or make a unique one for each? (I'm willing to make them if it's alright with asie)~~

Edit: Postponed icons to another time

### CODE REVIEW

**Comment by Prospector** [comment]
After discussing, for now the modules won't get icons. Maybe at a later date.

**Comment by sindrefag** [comment]
@Prospector what about doing it as simple as giving all mods which have no icon the fabric icon but with a random colour applied on top?

**Comment by Prospector** [comment]
That has nothing to do with this PR to Fabric API

**Comment by grondag** [comment]
I would like to see this merged because it will improve the user experience significantly for some players.  However, I'm a little wary of including mod-specific custom tags in the Fabric API itself.

That said, maybe there's a simple solution:  could we use `fabric-menu` as the namespace for the `api` and `parent` attributes instead of `modmenu`? 

The idea is to make these generic so that, theoretically, any menu-type mod could use them and Fabric doesn't appear to be endorsing a particular one. (To be clear, Mod Menu is great and I personally see no particular need for an alternative but thinking long-term.)

**Comment by liach** [comment]
so what will happen to the api instead? @Prospector

**Comment by Prospector** [comment]
Well this PR is superseded by https://github.com/FabricMC/fabric/pull/353 but as for the modmenu specific features...until someone adds the necessary stuff to Fabric Loader it will have to remain hardcoded in ModMenu I suppose.

**Pull request closed without merging**
