### PR TITLE
Add DataGeneratorEntrypoint.buildRegistry

### PR DESCRIPTION
**Pull request by modmuss50**
Used to allow data generation against custom dynamic registry entries such as biomes. Im not too happy with the way I build up the merge RegistryBuilder, I may revist this.

### CODE REVIEW

**Review by Technici4n — CHANGES_REQUESTED** [review]
Can I ask for the following structure to be used in the testmod, or close to that? This is probably what many people are going to reference, so it would be best to move all of the creation code out of the datagen entrypoint and make it more idiomatic. What do you think?

image

**Comment by Technici4n** [comment]
I think the new API is fine (just need to cleanup the testmod as I said above).

Not sure about the exact implementation of merging, but that can easily be improved later on without API breaks, so I wouldn't worry too much about it. :+1:

**Comment by modmuss50** [comment]
@Technici4n I have cleaned up the testmod a little, hopefully its a bit more clear now. 👍

**Review by Technici4n — COMMENTED** [review]
Thanks, looks nicer to me!

One last question: Minecraft initializes the RegistryLookup offthread (that's why it's a CF). Shouldn't we be doing the same? (Or did I misread the code?)

**Comment by modmuss50** [comment]
Done, I dont think its really needed but we might as well use it.

**Review by Technici4n — APPROVED** [review]

**Pull request merged**
