### PR TITLE
Update loom, use tinyv2 (for params/jd), update loader

### PR DESCRIPTION
**Pull request by liach**
The build passes, no worries

Signed-off-by: liach <liach@users.noreply.github.com>

### CODE REVIEW

**Comment by liach** [comment]
@natanfudge come take a look as well

**Review by modmuss50 — APPROVED** [review]
Looks fine to me, I assume you made sure it builds

**Comment by natanfudge** [comment]
Is there a special reason why not all fabric repos get automatic builds like yarn and loom?

**Comment by liach** [comment]
@modmuss50 A screenshot of successful build after rebase
image

**Comment by Player3324** [comment]
> Is there a special reason why not all fabric repos get automatic builds like yarn and loom?

API uses manual version increments, we figured it's easiest to do by triggering the build manually after adjusting everything instead of wasting hours on an imperfect automatic solution.

**Review by Player3324 — APPROVED** [review]

**Pull request merged**
