### PR TITLE
Add dispatch methods that take ByteBuf and wrap as PacketByteBuf

### PR DESCRIPTION
**Pull request by ChloeDawn**

### CODE REVIEW

**Review by Juuxel — APPROVED** [review]

**Comment by liach** [comment]
i personally fail to find this useful. why can't outer sources just wrap on their own?

**Comment by ChloeDawn** [comment]
> i personally fail to find this useful. why can't outer sources just wrap on their own?

They can if they desire, this is just a quality of life addition.

**Comment by liach** [comment]
To me, it only causes considerable confusion, just like how `void take(int[])` and `void take(String)` can both take `Object` and calls get confusing. It is not that hard to call `new PacketByteBuf()`.

**Comment by biom4st3r** [comment]
There have definitely been a couple times using building buffers with tail recursion that this would have been nice

**Pull request closed without merging**
