### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by XuyuEre**

### CODE REVIEW

**Comment by asiekierka** [comment]
@TriTUSK @liach

**Comment by liach** [comment]
this looks good, though I like `第 %d/%d 页` slightly better (doesn't really matter)

**Comment by 3TUSK** [comment]
If it were me I would go for `第 %d/%d 页`.

**Comment by asiekierka** [comment]
I think that's two to one. Is there precedent for either option?

**Comment by 3TUSK** [comment]
I would say it's a half-half split.

**Comment by asiekierka** [comment]
Perhaps we need to ask more translators?

**Comment by 3TUSK** [comment]
@TartaricAcid
Worth trying.

**Comment by shedaniel** [comment]
I agree with `第 %d/%d 页`

**Comment by XuyuEre** [comment]
Before I just followed the structure of the original text. `第 %d/%d 页` is better with Chinese player habits.

**Comment by liach** [comment]
:tada: Thanks asie and XuyuEre!

**Pull request merged**
