### PR TITLE
Fix AttackBlockCallback being fired for incorrect player actions

### PR DESCRIPTION
**Pull request by modmuss50**

### CODE REVIEW

**Comment by modmuss50** [comment]
This fixes wiggly flamigos

**Review by Juuxel — APPROVED** [review]
Looks good if the merge conflicts are fixed.

**Comment by modmuss50** [comment]
Yeah, I forked off the `master` branch....

**Comment by modmuss50** [comment]
I bumped the version to `0.3.0` as it could possibly be breaking, but I doubt that.

**Comment by liach** [comment]
Should be 0.2.8 as this is not touching the api part but only the implementation.

**Review by Player3324 — APPROVED** [review]

**Pull request merged**
