### PR TITLE
Add getters for equipment slot providers and damage handlers

### PR DESCRIPTION
**Pull request by Juuxel**
Some mods need to access these and there's also no reason to "hide" them from mod devs.

### CODE REVIEW

**Review by AlphaMode — COMMENTED** [review]
Can methods for getting the slot provider be added to FabricItem and FabricItemStack?

**Comment by Juuxel** [comment]
Not sure about FabricItem since it'd mean that it could be overridden which adds another way of registering the same thing.

As for FabricItemStack, it could actually have a method for getting the preferred equipment slot directly I think since you can apply the provider to `this` stack.

**Review by Technici4n — CHANGES_REQUESTED** [review]
May I suggest `ItemConvertible`?

**Comment by Technici4n** [comment]
> Not sure about FabricItem since it'd mean that it could be overridden which adds another way of registering the same thing.

Agreed, let's keep the APIs separate.

> As for FabricItemStack, it could actually have a method for getting the preferred equipment slot directly I think since you can apply the provider to `this` stack.

Why not just use the following `LivingEntity` method?
```java
    public static EquipmentSlot getPreferredEquipmentSlot(ItemStack stack) {
```

May I also ask what the point of exposing these is?

**Comment by Juuxel** [comment]
This was @AlphaMode's request, but I agree the LivingEntity method is probably better. The damage handler is just for the sake of completeness since it uses the same system to attach it to an item.

**Comment by Juuxel** [comment]
Closed in favour of a different approach (PR coming shortly).

**Pull request closed without merging**
