### PR TITLE
Entity Damage Event

### PR DESCRIPTION
**Pull request by dexman545**
An event for monitoring any entity's health being updated. 
Returns the entity's (new) health, but leaves tracking the difference in health and damage source to the dev.

### CODE REVIEW

**Comment by liach** [comment]
Imo this event has too little context... Maybe people want to check damage source on entity, etc.

**Comment by i509VCB** [comment]
The event needs more context for sure. I feel the event would do better with an, originalDamage parameter, currentDamage. 

And make the event return a TypedActionResult<Float> to specify the resulting damage of the event.

**Comment by liach** [comment]
> I feel the event would do better with an, originalDamage parameter, currentDamage.

The original health can be fetched from the passed entity directly.

**Comment by dexman545** [comment]
isn't `livingentity#getRecentDamageSource` sufficient to get that context?

**Comment by i509VCB** [comment]
Not really since someone may just call setHealth and fire the event the tick after the entity is spawned.

**Comment by dexman545** [comment]
And that should be fine? It would just return null. This is for whenever an entity's health changes, not just when it is damaged.

**Pull request closed without merging**
