### PR TITLE
Datagen stuff

### PR DESCRIPTION
**Pull request by Shnupbups**
Refactor names to match yarn pr https://github.com/FabricMC/yarn/pull/2905

Add TAWs for `BlockStateModelGenerator.blockStateCollector` and `BlockStateModelGenerator.modelCollector`

### CODE REVIEW

**Comment by Juuxel** [comment]
Ah yes, a breaking update <:concern:917342882074083389>

**Comment by Shnupbups** [comment]
No longer breaking, to be honest I wasn't thinking about that haha

**Comment by deirn** [comment]
For `FabricTagProvider` you also need to make deprecated inner classes and methods.

**Comment by NinjaPhenix** [comment]
Still a breaking change as you renamed the inner classes for tag providers.

**Comment by Shnupbups** [comment]
> For `FabricTagProvider` you also need to make deprecated inner classes and methods.

The inner classes of `FabricTagsProvider` are still accessible through the deprecated `FabricTagProvider` though?

**Comment by ghost** [comment]
> The inner classes of `FabricTagsProvider` are still accessible through the deprecated `FabricTagProvider` though?

You renamed the inner classes too though.

**Comment by Shnupbups** [comment]
> You renamed the inner classes too though.

Ah, so I did. Will fix!

**Comment by deirn** [comment]
Hmm actually, since `fabric-data-generation-api-v1` is a dev-only module, breaking changes shouldn't matter that much.

**Comment by Shnupbups** [comment]
Closing this in favour of 2 separate PRs, one for renames, another for additions

**Comment by Shnupbups** [comment]
Split into #1910 and #1911

**Pull request closed without merging**
