### PR TITLE
Simplify fabric-particles-v1 and fix sprites not being added to the particle sprite atlas

### PR DESCRIPTION
**Pull request by JamiesWhiteShirt**
As is tradition, particles require competing pull requests. This is an alternative to #527.

This implementation is simpler in the sense that it contains less logic duplicated from vanilla while still providing the full API introduced in #341. In some ways, this implementations bears similarities with #264. By staying closer to the vanilla particle system, this implementation also resolves the issue of sprites not being added to the particle texture atlas.

This simplification comes at the cost of some light reflection, which one could argue introduces a maintenance cost. However, I believe this implementation is more maintainable overall.

These changes were tested locally with a mod adding particles without issue.

[Based on this comment.](https://github.com/FabricMC/fabric/pull/527#issuecomment-600353164)

### CODE REVIEW

**Comment by ghost** [comment]
Might I add this pr would also be easier to maintain once AccessWideners are released (since the ctor could be made public without reflection). That being said I don't see reflection as a thing that should be avoided.

**Review by liach — APPROVED** [review]
Looks nice and clean!

**Review by biom4st3r — APPROVED** [review]
Looks simple and easy to maintain. Switching to an AW wouldn't really change much as the reflected code only runs at startup

**Review by Prospector — APPROVED** [review]
Looks way cleaner than the current fabric-particles 👍

**Comment by Prospector** [comment]
I mean an argument could definitely be made for using AWs instead, but I think it's fine either way tbh.

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
This is actually a small change, as only implementations are changed. No public api is changed. @sfPlayer1 mind review?

**Review by Pyrofab — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]
Testmod might be useful, but this seems good.

**Review by Yoghurt4C — APPROVED** [review]
The fabric-particles-v1 module has been broken for far too long,  so now we have a possibility of using a fabric-particle-v2. This would, of course, result in amazing situations. :D
Unlearning is not easy. I can see that many people tend to go through the motion of throwing up their hands.   I know it is difficult for many to try to break the habits.   However, doing so is required, if not achieved, we would surely be back to where we were last time.
For those who are reluctant to go through with this procedure, I will always be here.

**Review by LemmaEOF — APPROVED** [review]

**Review by hYdos — APPROVED** [review]

**Review by Player3324 — APPROVED** [review]

**Pull request merged**
