### PR TITLE
Several tag fixes and additions

### LINKED ISSUE #3869: Missing a few c tags,
These tags are missing: c:glass_blocks/colorless, c:ender_pearls

### LINKED ISSUE #3899: Fabric Standard Tags for Food are limited.
As i develop both datapacks & mods more, i am realizing it is important for modded Compatibility to have different tags for golden foods & normal foods. However, the current tags are used by many mods, and removing the normal tags would cause incompatibility when updating mods.

And for people who don't need this separation, the normal tags should still exist. 

Golden foods such as golden apple, enchanted golden apple, and golden carrot need too have a tag separate from the rest. and they also need to be included in the normal tag, used for targeting all fruits & vegies including golden.

I am opening a pull request myself, however as i am still new to the modding scene i'm not sure i did everything right. If this is the case, i would love to try to fix it myself, unless fabric peeps just wanna make the change thsemselves, but hopefully if i explain bad the PR should at least demonstrate what i want to happen.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Changes includes:

- Renaming all food tags under `c:foods/` to be singular. Example is `c:foods/fruits` to be `c:foods/fruit`. This is because you would say Fruit Foods and not Fruits Foods. Basically, foods is the noun. Fruit is the descriptor of the food noun. Backwards compat added here to reduce breakage for people.

- Added `c:foods/golden` to collect all gold based foods. Which then can be paired ingredient intersections and differences to target or exclude from the other food tags.

- Added `c:tools/igniter` to now have Flint and Steel be considered a tool properly.

- Adding `c:ender_pearls`, `c:glass_blocks/colorless`, `c:glass_blocks/cheap`, `c:glass_blocks/tinted`, `c:glass_panes/colorless` tags to match what Neoforge has closer.

Neoforge PR: https://github.com/neoforged/NeoForge/pull/1238

Closes: https://github.com/FabricMC/fabric/issues/3899

Closes: https://github.com/FabricMC/fabric/issues/3869

Closes half of : https://github.com/FabricMC/fabric/issues/3895

### CODE REVIEW

**Review by modmuss50 — APPROVED** [review]
Looks good, thanks for the contiuned support with this.

**Comment by TelepathicGrunt** [comment]
@modmuss50 One second, I'll deal with the merge conflicts

**Comment by TelepathicGrunt** [comment]
@modmuss50 Should be good now

**Comment by modmuss50** [comment]
Lol, I was doing the same :D Wondered why I couldnt push it lol. Thanks 👍

**Comment by ffuentesm** [comment]
does this mean the duplicated plural tags will be removed? 
Like how we still have c:foods/vegetables & c:foods/vegetable in the API.

**Comment by TelepathicGrunt** [comment]
@ffuentesm The deprecated (typoed) tags are to be removed in 1.22 iirc unless the fabric team prefers to remove it earlier. They were a mistake to begin with but removing them is a breaking change that fabric api is trying to avoid

**Pull request merged**
