### PR TITLE
Fix NPE in fluid renderer mixin

### PR DESCRIPTION
**Pull request by Virtuoel**
Fixes potential NPE when rendering non-vanilla fluids.

### CODE REVIEW

**Comment by modmuss50** [comment]
Why would this ever be null?

The state is coming from the last param of FluidRenderer.tesselate, and must be none null. Wouldnt it just crash later on in vanilla code?

**Comment by Virtuoel** [comment]
From some testing earlier, it seems to be null for fluids added by mods when they are outside the player's field of view.

**Comment by modmuss50** [comment]
Humm im struggling to see how it even gets that far as it would crash in ChunkRenderer first, have you got a crash log, or some way to reproduce this?

**Comment by Virtuoel** [comment]
I'll toss together a small test mod in a bit and put it on the Discord.

**Comment by modmuss50** [comment]
Just moving what @Virtuoel said on discord to here so it doesnt get lost.

> Ok, figured it out. The state itself is never null, but if the handler is null (e.g. if no render handler is set), the hook container's state will never be set and will stay as null. 
The hook container also is never null, making its null check redundant.

> To guarantee the contents of the hook container are never null, I've moved the setting of the hook container's view, pos, state, and handler to before the return. I've also removed the unnecessary null checks. The handler null check I've commented out as it seems to be more related with the other block of commented out code.
And previously, if a mod forgot to register a render handler for their fluid, the game would just crash instead of the old behavior of rendering the fluid as water.

[FluidRendererCrashTest-0.0.1.jar](https://ss.modmuss50.me/FluidRendererCrashTest-0.0.1.jar)

[source](https://gist.github.com/Virtuoel/d2a99047bb16f351f0d003643a828109)

I will take a closer look at this again.

**Review by liach — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]
Looks like the correct fix to me

**Comment by modmuss50** [comment]
Looks good, `handler` is safely handled if null in FluidRenderHandler

**Comment by modmuss50** [comment]
Before merging this needs a verison bump

**Review by Player3324 — APPROVED** [review]

**Comment by Player3324** [comment]
Thanks, I will take care of the 1.15 port.

**Pull request merged**
