### PR TITLE
Add @Nullable (jetbrains annotations)

### PR DESCRIPTION
**Pull request by natanfudge**
>org.jetbrains.annotations
Annotation Type Nullable
 
>@Documented
 @Retention(value=CLASS)
 @Target(value={METHOD,FIELD,PARAMETER,LOCAL_VARIABLE,TYPE_USE})
public @interface Nullable
An element annotated with Nullable claims null value is perfectly valid to return (for methods), pass to (parameters) or hold in (local variables and fields). Apart from documentation purposes this annotation is intended to be used by static analysis tools to validate against probable runtime errors or element contract violations. By convention, this annotation applied only when the value should always be checked against null because the developer could do nothing to prevent null from happening. Otherwise, too eager Nullable usage could lead to too many false positives from static analysis tools. For example, Map.get(Object key) should not be annotated Nullable because someone may have put not-null value in the map by this key and is expecting to find this value there ever since. On the other hand, the Reference.get() should be annotated Nullable because it returns null if object got collected which can happen at any time completely unexpectedly.

### CODE REVIEW

**Review by Ueaj-Kerman — APPROVED** [review]
🚲🏠

**Review by modmuss50 — CHANGES_REQUESTED** [review]
This isnt the solution. My idea was for loom to remap the existing annotations in the game to the chosen annotation lib.

Deciding if this is what is wanted needs to be done first, and then choosing a replacement lib.

**Comment by i509VCB** [comment]
Personally I think we need to decide this for all projects we maintain. The reason the earlier add annotations was closed is because we want to have the mapped jar in dev have the same annotations.

**Comment by Ueaj-Kerman** [comment]
does that need a specific library though, why can't the remapping be done to intellij annotations?

**Comment by grondag** [comment]
We eclipse users will not stand for this brazen Jetbrains tyranny!

(Nah, seriously, I don't care, just pick one.)

**Comment by i509VCB** [comment]
>We eclipse users will not stand for this brazen Jetbrains tyranny!

rofl

**Comment by ghost** [comment]
This should be closed it seems like the scope of this PR is now being fulfilled by #1007

**Comment by i509VCB** [comment]
Superseded by #1007

**Pull request closed without merging**
