### PR TITLE
Add minimal "getting started" to README.md

### PR DESCRIPTION
**Pull request by Lytigas**
After being completely lost trying to read some source code using only yarn, Masa directed me to the example mod to get my dev environment set up. I think it could be useful for discoverability to have it linked here.

### CODE REVIEW

**Comment by liach** [comment]
In my opinion, this should rather appear in fabric loader instead of here.

**Comment by Lytigas** [comment]
My thought is that people might find the fabric project GitHub through google/curseforge, and then end up seeing blank READMEs. Ideally something would go in both READMEs that explains some things. However, https://fabricmc.net/wiki/tutorial:setup might be a better place to go.

**Comment by asiekierka** [comment]
I think this is absolutely fine.

**Comment by sfPlayer1** [comment]
IMO such a section should be added to every project, we can't rely on outsiders knowing the structure/other projects. PR look ok to me

**Comment by Prospector** [comment]
Should just add a link to the wiki too

**Comment by grondag** [comment]
I'm counting this as approved by Player and Asie, given their comments. -> Last Call.

**Comment by liach** [comment]
i suggest an additional link to the wiki

**Comment by modmuss50** [comment]
Merged in manually here: https://github.com/FabricMC/fabric/compare/9b03381f03f4...9f55aa704f28

Thanks.

**Pull request closed without merging**
