### PR TITLE
Fix the onPlayerInteractEntity mixin causing a crash because the target method signature was not specified

### LINKED ISSUE #1360: Right clicking a villager leads to a game crash
After summoning a villager and right clicking him, the game crashed. This happened with 21w10a and Fabric API 0.32.1+1.17.

The villager did not have a job as it was newly summoned, not sure if having a job would change anything.

Crashlog see gist: https://gist.github.com/gbl/f41e79adb6aff024acbe5ee1f50a430d

### PR DESCRIPTION
**Pull request by haykam821**
Fixes #1360

### CODE REVIEW

**Review by liach — APPROVED** [review]

**Comment by liach** [comment]
Just curious, does mixin annotation processor warn when it finds multiple targets at compile time?

**Comment by haykam821** [comment]
Mixin provides a helpful warning for this scenario:

```
./fabric/fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/mixin/event/interaction/MixinServerPlayNetworkHandler.java:45: warning: @Inject target requires method signature because enclosing type information for net.minecraft.server.network.ServerPlayNetworkHandler$1 is unavailable
@Inject(method = "interactAt", at = @At(value = "HEAD"), cancellable = true)
```

**Comment by modmuss50** [comment]
Have you tested this out of dev?

**Comment by modmuss50** [comment]
Tested it myself, works fine. Thanks 👍

**Pull request merged**
