### PR TITLE
Loot table API v2

### PR DESCRIPTION
**Pull request by Juuxel**
- The main change is that v2 uses new 1.16 Yarn names for all methods, and the previously renamed `LootTable` instead of `LootSupplier` as well.
- All uses of reflection were removed.
- v2 supports the entire API of v1 with the exception of `LootJsonParser` and `LootEntryTypeRegistry` which have become useless in Minecraft updates. (Now you can just use `LootGsons` and `Registry.LOOT_POOL_ENTRY_TYPE` from vanilla.)
- Added a few new methods in `FabricLootPoolBuilder` that work with collections of children.
- Changes to v1:
  - v1 was retrofitted to always fall back to v2 when possible.
  - v1's `LootEntryTypeRegistry` was changed to directly register to the vanilla registry.

### CODE REVIEW

**Comment by frqnny** [comment]
I'm guessing this PR is to replace the dead PR of
#415

**Comment by Juuxel** [comment]
Partially, but this also covers more things.

**Review by Prospector — APPROVED** [review]
Glad to see all the nice names!

**Comment by i509VCB** [comment]
Needs to be merged with upstream to resolve conflicts.

**Comment by Juuxel** [comment]
I've merged this now.

**Review by i509VCB — APPROVED** [review]
Implementationwise it looks good. But I feel a big issue is that yarn has little to no loot table javadoc. It would be very useful as explaining the entire loot system in the class javadoc for this api would be a challange

**Comment by Juuxel** [comment]
@i509VCB Yeah, I agree. I'm going to make a Yarn PR that will document some of the most important loot classes. I do need to fix some of the names as well, though, since the current loot names are a bit of a mess in some places.

**Review by TiphaineLAURENT — CHANGES_REQUESTED** [review]
I would like to add the ability to create LootTable
I already wrote a mixin for this [there](https://github.com/TiphaineLAURENT/Builders-blocks/blob/master/src/main/java/net/tiphainelaurent/buildersblocks/mixin/LootTablesRegistrationMixin.java) (Block.LOOT_TABLES is defined in my [Block Builder class](https://github.com/TiphaineLAURENT/Builders-blocks/blob/a6f569a4dc0fa3f62f3cef52a6c8093b98afc498/src/main/java/net/tiphainelaurent/buildersblocks/api/helpers/Block.java#L32) and is juste a Map<Identifier, Supplier<LootTable>>).

I use it (can be an example) in [this same Block Builder class](https://github.com/TiphaineLAURENT/Builders-blocks/blob/a6f569a4dc0fa3f62f3cef52a6c8093b98afc498/src/main/java/net/tiphainelaurent/buildersblocks/api/helpers/Block.java#L113) to generate mineable blocks loottable.

What I am doing in this mixin is merging the new loottables with existing ones before Minecraft actually inject them in the game.
In term of code, I update the map of Json loottables from the LootManager.apply method at the head of the method.

**Comment by i509VCB** [comment]
@TiphaineLAURENT so essentially you would like a callback to notify you when to generate loot tables for the loot manager?

**Comment by TiphaineLAURENT** [comment]
@i509VCB Exactly.

**Comment by Juuxel** [comment]
@TiphaineLAURENT That's out of scope for this PR. The main aim of this PR is to bring the loot table API up to current Yarn names for the related vanilla code, and to do some quality-of-life improvements for the builder classes.

**Comment by Juuxel** [comment]
Replaced by #1241.

**Pull request closed without merging**
