### PR TITLE
Fixing registry id between server and client

### PR DESCRIPTION
**Pull request by sekwah41**
This seems to fix the id mismatching, cant find any problems so far but it feels too simple to be the complete solution.

Haven't found any problems with it so its likely the full fix for #88 (in terms of upcrafts comment)

### CODE REVIEW

**Comment by sekwah41** [comment]
If there is anything wrong with this I will happily take any issues found and try to do fixes for those too but it fixes the issue we were having on our modded server and also the mod I made specifically to forge a mismatch of ids.

**Comment by asiekierka** [comment]
That's not quite right.  The option is designed to add missing registry entries in the event of loading a registry file off-disk, *not* in the event of loading registry data off the network.

**Comment by sekwah41** [comment]
_well_ the code that was created for doing that is basically exactly what is needed to make those mapping line up. Any mappings not on the server get pushed to the back and all the known mappings get their correct values. What actually is wrong with it doing this? If the server has an extra mod that the client doesn't have then wouldn't there just end up being gaps in the registry? (I haven't tested that side yet)

**Comment by sekwah41** [comment]
What are the key differences needed between loading a mapping from a file vs loading the mappings from a server? I can take a crack at making the necessary changes.

Based on what that boolean is labelled as I don't get what behaviour would be unwanted. And if we are going to keep that false at least block the user from joining the server rather than throwing but letting them join anyway? I mean this is the main cause of the problem I am trying to address.
```Java
if (!reallocateMissingEntries && !idMap.keySet().equals(registry.getIds())) {
			throw new RemapException("Source and destination keys differ!");
		}
```

**Comment by asiekierka** [comment]
>I mean why block remapping a client which has more than just the mods needed?

Because the server has no idea what those numeric IDs mean, then. Can cause problems.

>throwing but letting them join anyway?

If the client is missing an ID declared by the server, that's what should happen, but I haven't had the time to do it yet. If the server is missing an ID declared by the client, I suppose it should just be hidden on the client?

**Comment by sekwah41** [comment]
> If the client is missing an ID declared by the server, that's what should happen, but I haven't had the time to do it yet. If the server is missing an ID declared by the client, I suppose it should just be hidden on the client?

Currently it does throw and let them join anyway hence the id mismatch, though I think we are getting a little confused with each others explanations possibly. I agree they should be able to join but the issue was it just doesn't map anything and rejects any mapping changes. From what ive seen the change i made does exactly what it should if the client has extra data the server doesn't except for the unmapped values it sounds like you want something else being done with them.

Are you suggesting something more along the lines of creating client copies of the registries and then comparing the server one on join and not storing any of the unmapped values in the registry? Or am I completely missing the mark?

> Because the server has no idea what those numeric IDs mean, then. Can cause problems.
Cant we make it return the for the registry's default value? I know some of the lists at least have default values e.g. block has AIR wouldn't that fix that problem even with the invalid ids?

**Comment by sekwah41** [comment]
Yea just checking, not sure about SimpleRegistry, that seems down to the individual use to handle that properly with nulls but DefaultedRegistry which is used for items and a fair few others I cant think of any case where that would cause any issues for the server if the client had extra mappings though you have more experience with this than me I assume.

**Pull request closed without merging**
