### PR TITLE
Expose BucketItem#fluid

### PR DESCRIPTION
**Pull request by Ueaj-Kerman**
I don't know why this is private, pretty odd, but me and others end up making accessors for this field. 
So I thought it might be nice to just add it to fapi to make it easier for everyone

### CODE REVIEW

**Comment by shedaniel** [comment]
AW isn’t transitive is it

**Comment by Ueaj-Kerman** [comment]
is it not, I thought it was

**Comment by vini2003** [comment]
in the name of god, in the name of the mighty lord, i approv

**Comment by Ueaj-Kerman** [comment]
nvm I don't think it's transitive

**Pull request closed without merging**
