### PR TITLE
Fix QuadEmitter#square and Indigo uv locking

### LINKED ISSUE #1024: QuadEmitter#sprite default implementation is broken
Here is my code:

https://github.com/Technici4n/fabric-rendering-issue/blob/master/src/main/java/net/fabricmc/example/FourSidedFurnaceModel.java

Result:
image

Expected result:
image

### PR DESCRIPTION
**Pull request by Technici4n**
Fixes #1024. Also, there was a mistake in the uv locking for the textures, which I fixed too.

### CODE REVIEW

**Comment by grondag** [comment]
Looks like an appropriate fix.  Could you provide some before/after screencaps?

**Comment by Technici4n** [comment]
Good idea indeed!

Before:
image

After:
image

- The wrong placement of the quads on the sides is fixed.
- The wrong UV for the top quad is fixed too.

PS: I've made sure that the new UVs match vanilla's!

**Comment by modmuss50** [comment]
Is this a breaking change?

**Comment by Technici4n** [comment]
Yes if people relied on the old behavior, but it's so broken I don't think anyone would have.

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
