### PR TITLE
Add Item tag for shears

### PR DESCRIPTION
**Pull request by Boundarybreaker**

### CODE REVIEW

**Comment by Yanis48** [comment]
Seems like a pretty simple PR to me, why is it not merged yet?

**Comment by Prospector** [comment]
Needs updating. Once it's updated I will promote it to last call.

**Comment by shedaniel** [comment]
Someone revive this I need to use this >:)

**Comment by Sollace** [comment]
OP seems dead. Perhaps we can combine this with a more comprehensive tags PR? There are quite a few block tags I could see being useful if Fabric were to add them besides other item tags.

**Comment by LemmaEOF** [comment]
Oh yeah, I never actually updated this to modularized fabric. I *do* have an open PR in the same module this got moved to, though, so I can do that pretty easily.

I don't think Fabric should add any other tags unless they're for specific API functions. The tools tags exist solely for the `FabricBlockSettings.breakByTool()` method, since that's not really something doable with other methods.

**Pull request closed without merging**
