### PR TITLE
Migrate to a modular JAR-in-JAR system, update to Loader 0.4.x

### PR DESCRIPTION
**Pull request by asiekierka**
AAAAAAAAAAAAAAAAAA

Still in development.

### CODE REVIEW

**Comment by modmuss50** [comment]
question, in loom modCompile deps are none transitive, how do you plan to handle this? Will we need to make some changes to loom?

**Comment by asiekierka** [comment]
Yes, probably.

**Comment by asiekierka** [comment]
THIS SOMEHOW WORKS KIND OF A LITTLE BIT

My complaints regarding the module split:

* fabric-client-models/textures, but fabric-registry-client.
* fabric-registry-client feels like a kludge of semi-unrelated, but small features.
* fabric-registry-extras could use a better name; it's for additional vanilla registries for content not covered by tags (fuel, flammables, composting...)
* fabric-mining-levels needs a better name; it's generally for controling "what tools can break what", but it also defines tool tags and will eventually offer helpers for checking "what tool can break what" as the vanilla way is a bit kludge-y

**Comment by Prospector** [comment]
`fabric-client-models/textures` -> `fabric-models/textures` - Client is simply unnecessary 
`fabric-registry-client` I think is fine actually, as they are simply clientside registry
`fabric-registry-extras` -> `fabric-additional-registries`
`fabric-mining-levels` -> `fabric-tool-hooks`

**Comment by asiekierka** [comment]
I'd actually propose:

* ``fabric-registry-client`` -> ``fabric-render-registries``
* ``fabric-registry-extras`` -> ``fabric-content-registries``
* ``fabric-registry-tags`` -> ``fabric-tag-registries``

**Comment by Prospector** [comment]
and `fabric-registry-commands` -> `fabric-commands-registry`?

**Comment by asiekierka** [comment]
Just ``fabric-commands``.

**Comment by modmuss50** [comment]
`fabric-commands` is good
`fabric-tag-registries` do you need the registries? just `fabric-tags`?
`fabric-content-registries` make more sense.

once this is done a wiki page can be made covering each module

**Comment by asiekierka** [comment]
``fabric-tags`` would sound like it provides all Fabric-owned tags, not just the registry; and frankly, I'm torn here (the currently implemented approach is to have, say, fabric-mining-levels provide tool tags, etc).

**Comment by Prospector** [comment]
I think the actual tags should be in every fabric distribution or with the resources module.

**Comment by asiekierka** [comment]
Being in 03x-refactor equals being in every Fabric *distribution*. The resources module is for loading resources by mods and should not provide any content.

**Comment by asiekierka** [comment]
Since I don't want this to diverge significantly from the 0.2.x tree (and I'd like to unblock further development), I propose 0.3.0-pre as a way to mark the initial 0.3.0 builds without guarantee of submodule names persisting as-is, after this first batch of renames. (Things will become clearer once I clear up some PRs anyway). Thoughts?

**Comment by modmuss50** [comment]
Sounds good, getting things moving again will help.

**Comment by asiekierka** [comment]
AAAAAAAAAAAAAAAA

**Pull request closed without merging**
