### PR TITLE
Fix Mixin Conflict with OptiFine pre10

### PR DESCRIPTION
**Pull request by qouteall**
(I haven't tested it) (Maybe it's not the sole conflict with optifine pre10)

### CODE REVIEW

**Comment by liach** [comment]
Shouldn't this be a job of optifabric?

**Comment by qouteall** [comment]
It's very hard for optifabric itself to resolve this conflict.

**Comment by qouteall** [comment]
Context: This is the OptiFine-patched stitch method
```
   public SpriteAtlasTexture.Data stitch(ResourceManager resourceManager, Stream idStream, Profiler profiler, int mipmapLevel) {
      this.terrain = this.id.equals(BLOCK_ATLAS_TEX);
      this.shaders = Config.isShaders();
      this.multiTexture = Config.isMultiTexture();
      int mipmapLevels = mipmapLevel;
      this.mapRegisteredSprites.clear();
      this.mapMissingSprites.clear();
      this.counterIndexInMap.reset();
      profiler.push("preparing");
      Set set = (Set)idStream.peek((p_229222_0_) -> {
         if (p_229222_0_ == null) {
            throw new IllegalArgumentException("Location cannot be null!");
         }
      }).collect(Collectors.toSet());
      Config.dbg("Multitexture: " + Config.isMultiTexture());
      TextureUtils.registerCustomSprites(this);
      set.addAll(this.mapRegisteredSprites.keySet());
      Set locsEmissive = newHashSet(set, this.mapRegisteredSprites.keySet());
      EmissiveTextures.updateIcons(this, locsEmissive);
      set.addAll(this.mapRegisteredSprites.keySet());
      if (mipmapLevel >= 4) {
         mipmapLevels = this.detectMaxMipmapLevel(set, resourceManager);
         Config.log("Mipmap levels: " + mipmapLevels);
      }
```

**Comment by modmuss50** [comment]
Removed the optifine code, I would prefer it to be fixed in optifabric. I’ve not had the chance to look at the lastest version.

**Comment by qouteall** [comment]
ok

**Pull request closed without merging**
