### PR TITLE
Add a way to retrieve the current MinecraftServer instance

### PR DESCRIPTION
**Pull request by MisterPeModder**
Adding a class called ServerProvider can retreive the current MinecraftServer instance.

### CODE REVIEW

**Comment by asiekierka** [comment]
This assumes there's only one. While this generally is true in practice, not so sure about theory...

It's better to get the server instance from a ServerWorld, or perhaps a PacketContext (do we expose it?).

**Comment by MisterPeModder** [comment]
Hmm I haven't thought about that...
It may be a good idea to expose the server from PacketContext tough.
But I see no other way of retrieving dimensions without the server instance.

**Comment by liach** [comment]
did vanilla remove this because the server retrieved at different times may be different instances?

**Comment by MisterPeModder** [comment]
On dedicated servers, there is only one instance and on clients a server is created on world loading, but as far as I can see, it seems there always is one server at a time.

**Comment by liach** [comment]
You can add a check that ensures the instance is not already set if the setter is called with a non-null arg

**Comment by MisterPeModder** [comment]
It's a pretty good idea

**Comment by SquidDev** [comment]
I believe it's already possible to access the current server using `FabricLoader.INSTANCE.getEnvironmentHandler().getServerInstance()`. This raises a couple of questions:
 - Do we need two ways to get the current server instance?
 - If not, would it be worth phasing out the Fabric loader equivalent?

**Comment by MisterPeModder** [comment]
I did not know about this... I'm closing this PR

**Pull request closed without merging**
