### PR TITLE
Mixin Refactors take 2

### PR DESCRIPTION
**Pull request by Shnupbups**
old one ( #1025 ) became riddled with merge conflicts

### CODE REVIEW

**Review by i509VCB — CHANGES_REQUESTED** [review]
@Shnupbups You should include changes to the checkstyle file for enforcing the `Accessor` and `Mixin` suffixes in the `mixin` package.

Once you do this then I feel this pull request will make sense.

Oh documentation for checkstyle stuff is here:
https://checkstyle.org/config_naming.html

**Comment by Ueaj-Kerman** [comment]
Access > Accessor iritat

**Review by modmuss50 — APPROVED** [review]

**Comment by modmuss50** [comment]
Would be great to have the checkstyle on this.

**Review by frqnny — COMMENTED** [review]
I think this should have been broken up into maybe 3 or 4 PRs, but whatever.

**Review by ghost — APPROVED** [review]
Looks good, merge conflicts need resolving and I'm still of the opinion that this should be merged as is as this PR has nothing to do with checkstyle.

**Review by YanisBft — APPROVED** [review]

**Comment by i509VCB** [comment]
This is going to be impossible to easily fix - so this will be closed.

A better solution may be to enforce the standards in new modules by codifying them first. This will come with a conventions doc hopefully in the next few days

**Pull request closed without merging**
