### PR TITLE
add (currently draft/internal) networking handshake API

### PR DESCRIPTION
**Pull request by asiekierka**
Other changes:

* Mark the EntityTracker mixin in fabric-networking as optional (it only adds internal APIs, and the method using them has a fallback)
* Clean up fabric-registry-sync a little

### CODE REVIEW

**Comment by asiekierka** [comment]
What this PR is missing:

* Parsing the fabric:hello handshake data and exposing them to mods (much like canPlayerReceive/canServerReceive)

What future PRs could do:

* Expose the login handshake API in some fashion (it runs in lockstep, so I'd rather have people append stuff to fabric:hello than push their own packets)
* fabric-registry-sync could then check for presence of a matching version of itself, and reject connections which won't sync correctly (registry mismatches)
* Add a way for mods to declare networking protocol version conflicts in fabric:hello?
* Split the server->client receiving and client->server sending part into two distinct classes as fabric-networking-v1; deprecate fabric-networking-v0

**Comment by liach** [comment]
@asiekierka Would you mind if we replace this pr with #455 instead?

**Comment by i509VCB** [comment]
Should we close this since #455 is basically a replacement or will we wait till #455 is merged.

**Comment by liach** [comment]
Closing as this is superseded effectively.

**Pull request closed without merging**
