### PR TITLE
Add crop and nugget tags

### LINKED ISSUE #4005: Tags for iron and gold nuggets
Like the gold and iron ingot tags, Fabric (and NeoForge) should define `c:nuggets/iron` and `c:nuggets/gold` that contain the vanilla items.

### PR DESCRIPTION
**Pull request by Juuxel**
Closes #4005.

Adds the tags
- `c:nuggets/iron`, `c:nuggets/gold`
- `c:crops`, containing:
  - `c:crops/beetroot`
  - `c:crops/cactus`
  - `c:crops/carrot`
  - `c:crops/cocoa_bean`
  - `c:crops/melon`
  - `c:crops/nether_wart`
  - `c:crops/potato`
  - `c:crops/pumpkin`
  - `c:crops/sugar_cane`
  - `c:crops/wheat`

Everything except some crop tags are already in NeoForge, but they're similar to the current ones.

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
cocoa beans make sense to me. Adding it to neo here. You can merge on fabric side if you all are good with your pr and neo will follow suit
https://github.com/neoforged/NeoForge/pull/1432

**Review by TelepathicGrunt — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Comment by TelepathicGrunt** [comment]
would it be worth us adding `c:crops/pumpkin` and `c:crops/melon` to further flesh out the crops tag of harvestable non-edible stuff from plants? (melon being the fully blockitem melon since silk touch can drop it. Melon slice is already in a food tag)

**Comment by Juuxel** [comment]
That makes sense to me. (The melon blocks too, they're like pumpkins vs carved pumpkins imo.) Should I add them here since the PR is already in last call or make a new PR?

**Comment by TelepathicGrunt** [comment]
Up to you or modmuss. I'm fine either way

**Review by TelepathicGrunt — APPROVED** [review]

**Comment by TelepathicGrunt** [comment]
neo pr updated to match new crop tags

**Pull request merged**
