### PR TITLE
Resource Condition: `fabric:never`

### PR DESCRIPTION
**Pull request by ghost**
Fabric equivalent of `forge:false`. Prevents a resource from being loaded.

Most common use case would be mods disabling specific vanilla recipes that don't go along with their mod.

Also added a helper data gen method,`FabricRecipeProvider#disabled`, and moved `ResourceConditionsImpl#featuresEnabled` directly under other json providers, before condition implementations, to match the rest of the file.

By the way, `DefaultResourceConditions#never` can be a field since it has no properties. Wanted to ask this because there isn't any other conditions like this.

### CODE REVIEW

**Comment by haykam821** [comment]
I don't see the use case as recipes can be disabled through other means already. Also, wouldn't this condition just cause the recipe to default to whatever was loaded in a lower priority data pack?

**Comment by JieningYu** [comment]
> I don't see the use case as recipes can be disabled through other means already. Also, wouldn't this condition just cause the recipe to default to whatever was loaded in a lower priority data pack?

for example: use a datapack to remove a recipe

**Comment by apple502j** [comment]
Can't we use resource filter in `pack.mcmeta`?

**Comment by haykam821** [comment]
I agree with @apple502j; using filters should be the recommended way to accomplish this goal. For example, `pack.mcmeta` could include the following to remove the beacon recipe:

```json
{
	"filter": {
		"block": [
			{
				"namespace": "minecraft",
				"path": "recipes/beacon\\.json"
			}
		]
	}
}
```

**Comment by Technici4n** [comment]
How do these filters scale if you need to filter out 100s of recipes?

BTW, this can also be accomplished by using the `or` condition with no inner conditions.

**Comment by ghost** [comment]
Oh I didn't know that filtering thing. If that's possible, then yeah this isn't really necessary.

**Pull request closed without merging**
