### PR TITLE
fix: floral tag missing meadow biome

### PR DESCRIPTION
**Pull request by maityyy**
https://minecraft.fandom.com/wiki/Meadow
> filled with patches of flowers

### CODE REVIEW

**Review by Technici4n — APPROVED** [review]

**Review by Juuxel — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Comment by Technici4n** [comment]
So, do we add lush caves to this tag or not?

**Comment by maityyy** [comment]
> So, do we add lush caves to this tag or not?

I am not sure, but of all the blocks in this biome, only `flowering_azalea_leaves` is a flower, since it is in the `flowers` tag

**Comment by maityyy** [comment]
More likely no than yes

**Comment by Technici4n** [comment]
Alright then this is fine

**Pull request merged**
