### PR TITLE
Various Indigo Improvements

### PR DESCRIPTION
**Pull request by grondag**
This PR resolves the following issues:
#199  Vanilla Bug: Glowstone creates AO shade
#289  Rendering on the Cutout and Transparent Layers together interferes with water rendering
#290  Smooth lighting breaks on continuous angled surfaces
#291  QuadEmitter not cleared on MeshBuilder.build()
#292  Render context QuadEmitter crash with flat lighting
#293  Relax vertex order requirements for modded quads

It also removes some unused declarations and bumps the Indigo build number to 0.1.8.

[A test build is available](https://github.com/grondag/fabric/releases/download/indigo-0.1.8-rc4/fabric-renderer-indigo-0.1.8+7070da39.jar).

You'll also need this [Test build of OptiFabric ](https://ss.modmuss50.me/optifabric-0.4.0-test2.jar)

Edit:  this PR now also improves compatibility with Optifine shaders.  Renderer features should remain intact.  Chunk loading is 15% to 20% slower when compatibility is enabled because of more conservative BufferBuilder input methods.   Test build is updated also.

### CODE REVIEW

**Comment by grondag** [comment]
> ... Are you sure vanilla doesn't check the light level for ao? It definitely did in older versions.

Yep. The current vanilla check is simply this:
```java
public float getAmbientOcclusionLightLevel(BlockState blockState_1, BlockView blockView_1, BlockPos blockPos_1) {
      return isShapeFullCube(blockState_1.getCollisionShape(blockView_1, blockPos_1)) ? 0.2F : 1.0F;
}
```

It's overridden for glass, but not for any luminous blocks.  Obviously there are other ways to patch this, but was going for something minimally invasive.  Won't be surprised if Mojang changes it eventually.

**Comment by grondag** [comment]
Hold off on merging this - I expected the OptiFine buffering fix to be a big deal but it ended being almost trivial.  May as well go as part of 1.8 - will cause less confusion/updating.

**Comment by asiekierka** [comment]
@grondag Looks good to me, but:

(a) I still don't like the force-compatibility key name...
(b) Do we *need* to tie "always-tesselate-blocks=false" and the vertex format compatibility code together? Is it done for performance reasons or...?

**Comment by grondag** [comment]
> (a) I still don't like the force-compatibility key name...

You've not said why except that it is vague, which is... vague. :-). 

The word "force" is used because this will override any configuration settings set by the user in the property file.  Otherwise I'd call it `compatibility-mode`.

> (b) Do we _need_ to tie "always-tesselate-blocks=false" and the vertex format compatibility code together? Is it done for performance reasons or...?

Probably not.  It's not faster and if this patch works it should always work.  I left it in only because that's the status quo and I haven't done extensive testing with multiple shader packs.  Given that users can still set it if needed, I favor removing it now that you mention it.

That said, the `force-compatibility` feature is implemented so that OptiFabric or any other mod using it can express their intent (ensure maximum compatibility) without needing to know or specify the details of how this is done.  

Future versions of Indigo might might add or remove configuration choices related to compatibility in response to changes made by Mojang or OF. Offering a single `force-compatibility` setting allows us to manage this without requiring updates or breaking changes in any mod using this feature.

If we *want* the compatibility choices to be managed externally then we should expose a generic configuration API that allows user configuration choices to be overridden, but that will also require more complicated semantics and decision logic for what happens if more than one mod tries to overwrite the same setting.  And we don't even have a proper configuration system yet - it's just a properties file.

**Comment by modmuss50** [comment]
For anyone that wants to test this, I have linked bellow a test version of OptiFabric.

[optifabric-0.4.0-test2.jar](https://ss.modmuss50.me/optifabric-0.4.0-test2.jar)

**Comment by Dinolek** [comment]
optifabric-0.4.0-test2.jar
fabric-renderer-indigo-0.1.8+bd57b436.jar

Doesn't work without disabling always-tesselate.
I get this on internal shaders:

**Comment by grondag** [comment]
@Dinolek Thank you for the report.  Was unable to reproduce with internal shaders.  Could you please provide your log, fabric settings and optifine config files?  My stuff is below.

Unfortunately, setting `always-tesselate-blocks` doesn't fix anything, it just masks whatever problem there is.  If it doesn't work without that, then modded blocks using the API won't be rendered properly.



```
#Indigo properties file
#Sun Jul 07 07:06:38 PDT 2019
always-tesselate-blocks=auto
ambient-occlusion-mode=hybrid
fix-smooth-lighting-offset=auto
fix-luminous-block-ambient-occlusion=auto
debug-compare-lighting=auto
fix-exterior-vertex-lighting=auto
```

[optionsof.txt](https://github.com/FabricMC/fabric/files/3365719/optionsof.txt)
[optionsshaders.txt](https://github.com/FabricMC/fabric/files/3365720/optionsshaders.txt)
[latest.log](https://github.com/FabricMC/fabric/files/3365723/latest.log)

**Comment by Dinolek** [comment]
[latest.log](https://github.com/FabricMC/fabric/files/3365737/latest.log)
[optionsof.txt](https://github.com/FabricMC/fabric/files/3365738/optionsof.txt)
[optionsshaders.txt](https://github.com/FabricMC/fabric/files/3365739/optionsshaders.txt)

**Comment by grondag** [comment]
Hmmm, log looks OK.  Configs match.  I wonder if this is OS-specific. 

That would suck, but looks like I need to fire up my linux box in a bit.

**Comment by calloatti** [comment]
https://paste.ee/p/klRWy

  fabric-api-0.3.0+build.188
  fabric-renderer-indigo-0.1.8+bd57b436
  optifabric-0.4.0-test2
  OptiFine_1.14.3_HD_U_F1

**Comment by Blayyke** [comment]
> 
> 
> https://paste.ee/p/klRWy
> 
> Windows 10
> 
> fabric-api-0.3.0+build.188
> fabric-renderer-indigo-0.1.8+bd57b436
> optifabric-0.4.0-test2
> OptiFine_1.14.3_HD_U_F1
> 
> 

I am also having this on Windows 10 with AMD Rx480 & i3-6100

**Pull request closed without merging**
