### PR TITLE
Preventing END special events with dimensional api

### PR DESCRIPTION
**Pull request by kohanis**

### CODE REVIEW

**Comment by kohanis** [comment]
Not sure about moveToWorld mixin, but probably most elegant one, and EntityMixin class name

**Comment by frqnny** [comment]
Could you elaborate a bit on what this does? What are you trying to accomplish?

**Comment by kohanis** [comment]
> Could you elaborate a bit on what this does? What are you trying to accomplish?

When using current dimension api for tp player to End or from End to Overworld it triggers End specific events like obsidian platform generation or endgame screen. These mixins should prevent it

**Comment by kohanis** [comment]
Style errors, got it. Will fix at home

Although style test passed locally. Does maven publishing have stricter rules?

**Comment by modmuss50** [comment]
No, run `gradlew checkstyle` or just do a full build via gradle.

**Comment by kohanis** [comment]
Should be fine now

**Comment by LordDeatHunter** [comment]
Any thoughts on when/if this will be merged?
I have an issue in waystones relating to this, and I'd like to know whether to implement a fix on my end.
LordDeatHunter/FabricWaystones#90

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
