### PR TITLE
[1.20.2] Remove login networking APIs

### PR DESCRIPTION
**Pull request by modmuss50**
The hope is all mods that use these APIs can move over to using the configuration networking APIs. Please do let me know if you have a usecase for these APIs that cannot be done during the configuration phase. I look forward to discussion about this idea.

### CODE REVIEW

**Review by apple502j — APPROVED** [review]

**Comment by liach** [comment]
I strongly disagree. This API is useful for communication with proxy servers during authentication, such as velocity; for instance, see https://github.com/OKTW-Network/FabricProxy-Lite/blob/00bcc13ca17093845a77ce5fbf18e646cee28f60/src/main/java/one/oktw/FabricProxyLite.java#L28-L30

**Comment by apple502j** [comment]
Good point. Guess we should maybe put Deprecated instead temporarily? The majority of uses would be replaceable with config phases, but the minority we cannot ignore.

**Review by apple502j — CHANGES_REQUESTED** [review]
Retracting approval.

**Comment by liach** [comment]
A way to manually introduce an incompatibility is to change the signature of the packet handlers, such as using the new CustomPayload or dropping MinecraftServer instance when ServerLoginNetworkHandler is available (ask to use ServerLoginNetworking.getMinecraftServer instead)

**Comment by apple502j** [comment]
Tbh, getMinecraftServer should also be removed. We have TAW now :)

**Comment by modmuss50** [comment]
I think its fine to keep it as-is, no point in breaking it for the point of it. Thanks @liach for pointing out that usecase 👍

**Pull request closed without merging**
