### PR TITLE
Add Access Widener for EntityModelLayers functions

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
This PR add somes AW for EntityModelLayers functions like `registerMain`, `register`, etc...

That can be usefull for custom entity model in 1.19.

### CODE REVIEW

**Comment by Technici4n** [comment]
Two things:
- If you don't use transitive access wideners, they can't be used in dependent mods, which defeats the point.
- This should like go in the transitive access widener module instead.

**Comment by Mysterious-Dev** [comment]
> Two things:
> 
>     * If you don't use transitive access wideners, they can't be used in dependent mods, which defeats the point.
> 
>     * This should like go in the transitive access widener module instead.

This is changed.

**Comment by Technici4n** [comment]
You added them to the wrong file I believe, there should be a template instead. Make sure to add to the template and run the task to update the autogenerated file. This file is autogenerated and should not be edited manually.

**Comment by Mysterious-Dev** [comment]
> You added them to the wrong file I believe, there should be a template instead. Make sure to add to the template and run the task to update the autogenerated file. This file is autogenerated and should not be edited manually.

Done, normaly ^^

**Review by Technici4n — APPROVED** [review]
I think this is good now, thanks!

**Comment by deirn** [comment]
All `EntityModelLayers` methods create `EntityModelLayer` with `minecraft` namespace, I don't think we want modders to do that.

From what I can tell, registering `EntityModelLayer` is more involved than calling one of those methods, we need to modify the map `EntityModels#getModels` returns. Fabric API already provide [`EntityModelLayerRegistry`](https://github.com/FabricMC/fabric/blob/1.19/fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/EntityModelLayerRegistry.java) for that.

**Pull request closed without merging**
