### PR TITLE
Fix memory leak by using weak set for ArrayBackedEvent list

### PR DESCRIPTION
**Pull request by BasiqueEvangelist**
~~Not completely tested right now, pinging @gliscowo for it™~~ Tested

### CODE REVIEW

**Comment by BasiqueEvangelist** [comment]
I've tested this with owo-lib, and this works: events aren't leaked anymore, even if I open screens
(top is before, bottom is after)
image image

**Review by apple502j — APPROVED** [review]
LGTM. We should probably deprecate-for-removal `EventFactory#invalidate`, the only code using this field and is not used by any mods.

**Review by Technici4n — APPROVED** [review]
This will do for now. Let's also note that this is completely not thread-safe even though the rest of event creation is.

**Comment by SquidDev** [comment]
You could use `new MapMaker().weakKeys().makeMap()` instead of `WeakHashMap` to make it thread safe, but it may not be worth the bother.

**Comment by Technici4n** [comment]
That's a good idea and it should probably be done just in case.

**Review by Player3324 — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
