### PR TITLE
Fix #2805: Fabric API deleting custom dimensions

### LINKED ISSUE #2805: Fabric API breaks Custom Dimensions
I'm building a datapack with custom dimensions (including custom biome & noise settings). Once i noticed that if i rejoin world, the custom dimensions disappear. I've investigated that dimensions disappear from level.dat file as soon as I open world from game or starting the server.
This behavior doesn't applies for vanilla / paper / fabric without fabric-api.
I know that this features are experimental, but I hope it will be fixed later.

### PR DESCRIPTION
**Pull request by Technici4n**
The bugfix introduced in #2078 caused dimensions added through 1.19 world presets to be removed when they're loaded, but they don't get added back! I think we should remove this mixin until we can find a fix that doesn't risk breaking vanilla.

### CODE REVIEW

**Comment by qouteall** [comment]
I am sorry for that. In 1.19.3 MC's dimension searialization changes and that may be not useful now. I am going to look into it.

**Comment by qouteall** [comment]
https://github.com/FabricMC/fabric/issues/2805

**Comment by qouteall** [comment]
https://github.com/FabricMC/fabric/pull/2856

**Comment by Technici4n** [comment]
Superseded by https://github.com/FabricMC/fabric/pull/2856.

**Pull request closed without merging**
