### PR TITLE
Fix sendError discrepency with client commands

### PR DESCRIPTION
**Pull request by jpenilla**
This fixes a discrepancy between how error messages are formatted in client commands vs server commands.

### CODE REVIEW

**Comment by i509VCB** [comment]
Could you attach a screenshot of before and after?

**Comment by Technici4n** [comment]
What is the difference?
Edit: i5 was first.

**Comment by jpenilla** [comment]
Yeah, give me a minute, will attach screenshots and test code

**Comment by jpenilla** [comment]
```java
new LiteralText("Invalid Command Syntax. Correct command syntax is: ")
        .append(
                new LiteralText(String.format("/%s", e.getCorrectSyntax()))
                        .styled(style -> style.withColor(Formatting.GRAY))
        )
```
Before: image
After: image

**Review by i509VCB — APPROVED** [review]

**Comment by LambdAurora** [comment]
I wonder if `shallowCopy` would be better.

It looks nicer than a `new LiteralText("").append()`.

**Comment by Technici4n** [comment]
What is the problem? Does `copy()` not perform a deep copy?

**Comment by LambdAurora** [comment]
> What is the problem? Does `copy()` not perform a deep copy?

It doesn't, it's even in [the javadoc](https://maven.fabricmc.net/docs/yarn-21w10a+build.1/net/minecraft/text/Text.html#copy()).

**Comment by Technici4n** [comment]
Ohhhh nice javadoc link. 😄
I'm all for `.shallowCopy()` then.

**Comment by jpenilla** [comment]
Using `shallowCopy()` would probably produce a visually similar result in the provided example, but would still be a discrepancy from `ServerCommandSource`. Instead of creating an empty component with a style and adding the message as a child, we would be modifying the style of the message, which with an example like 
```java
new LiteralText("Blue error")
        .styled(style -> style.withColor(Formatting.BLUE))
```
would produce a visually inconsistent result from `ServerCommandSource`.

**Review by Technici4n — APPROVED** [review]
Let's match vanilla behavior.

**Review by LambdAurora — APPROVED** [review]

**Review by liach — APPROVED** [review]
Looks good, based on the assumption that the top level literal text may be modified the rest of the message won't be modified.

**Review by modmuss50 — APPROVED** [review]

**Comment by modmuss50** [comment]
Tiny bug fix, I dont see a reason to do a release just for it. Will pull it in with the next batch of changes. 👍

**Review by Juuxel — APPROVED** [review]

**Pull request merged**
