### PR TITLE
Fix dedicated server commands (#93)

### PR DESCRIPTION
**Pull request by modmuss50**
I see room for improvement with the command api, I may open another pr that includes some breaking changes to get some feedback.

### CODE REVIEW

**Comment by asiekierka** [comment]
This looks like an odd solution to me. Why wouldn't ServerCommandManager do its job here?

**Comment by modmuss50** [comment]
On a dedicated server ServerCommandManager is loaded before the mods onInitialize method.

This injection point happens after the mods have been loaded

**Comment by asiekierka** [comment]
Ahh, gotcha.

**Comment by asiekierka** [comment]
In this case, add an "if (!dedicated)" to the other mixin - so that we don't get duplicates in case this behaviour changes

**Comment by modmuss50** [comment]
Done

**Pull request merged**
