### PR TITLE
Make BlockApiLookup expose the API and context classes

### LINKED ISSUE #1464: API Lookup should expose the API and context type
It's useful for anyone using API API beyond the simple use case.

For example, while trying to dispatch API queries to AE2 parts, I noticed that I need to get the context class to check if it's `AEPartLocation` or `Direction`: https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/5711bbc8ffaeb25ada8149cb5f674d3e699eb3d6/src/api/java/appeng/api/parts/PartApiLookup.java#L38. (warning: most of the code is MCP, but not this file).

In this case I could also ask for the context as an additional parameter, but it's redundant and I think it's a good API API addition. I am opening this to remember. I will update #1352 as well soon:tm:.

### PR DESCRIPTION
**Pull request by Technici4n**
Closes #1464. I had a few minutes to write this, not high priority but at the same time very simple.

### CODE REVIEW

**Review by liach — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Review by Player3324 — APPROVED** [review]

**Comment by Player3324** [comment]
Considering it's a mixed class the get prefixes would be required, but it may cause confusion with the regular get()

**Comment by liach** [comment]
Last call this? The compatibility impact should be minimal.

**Comment by Player3324** [comment]
It's too minor for the last call process imo

**Comment by Technici4n** [comment]
Hmmm yes, I think omitting the `get` prefix is better to avoid confusion.

**Comment by Technici4n** [comment]
No need for last call, we just need to agree on the get prefix. Imo both options are equally suitable.

**Comment by liach** [comment]
Related: FabricMC/yarn#2408

Another remark: this api and context classes are immutable.
Also, how about kotlin usages?

**Comment by Technici4n** [comment]
Hmmm let me add the get prefixes then, it will be better for consistency.

**Comment by Technici4n** [comment]
image

Actually no, this is a better separation. Arghhh I don't know 😆

**Comment by Technici4n** [comment]
image

This is with the `get` prefixes... I'm in favor of not adding them, and we can merge this PR then. 👍

**Comment by liach** [comment]
Yeah, I just added that link for referential purposes. Jdk does not use get prefix for such immutable properties mostly, and I agree with your decision of no extra `get`.

**Pull request merged**
