### PR TITLE
Add 2020 to license headers

### PR DESCRIPTION
**Pull request by YanisBft**
Probably the most controversial PR in this repo

### CODE REVIEW

**Review by shedaniel — APPROVED** [review]
Looks nice, how do we bikeshed this though

**Comment by liach** [comment]
Maybe we should just use the initial year 2016 as in the loader

**Review by Pyrofab — COMMENTED** [review]
Too big to review, you should try breaking it up into smaller PRs

(/s)

**Review by liach — CHANGES_REQUESTED** [review]
We should just remove the year from copyright notice

**Comment by dblsaiko** [comment]
> Looks nice, how do we bikeshed this though

I'd replace "2016, 2017, 2018, 2019" with "2016-2020". That way it'll still say effectively the same thing but the text won't get longer every year.

**Comment by Prospector** [comment]
Ideally it would only include the years that particular file was modified in, but that's not really feasible.

**Comment by dblsaiko** [comment]
It's not?

```
zx@invader ~/code/minecraft/fabricdev/fabric (git)-[1.16] % git log --follow --format=%as build.gradle | cut -c-4 | sort -u | paste -sd ',' - 
2018,2019,2020
```

With a bit more work, this could be converted into a shellscript that goes through all java files and updates the license header

**Comment by Player3324** [comment]
That is not how license headers work, adding a year just because is pointless and counter-productive. I generally favor no license header at all or the Oracle/JDK's model  which records the original creation year of the file and the last significant modification's year. The value of this is incredibly limited though since in practice copyright lasts forever anyway.

**Comment by modmuss50** [comment]
I think file creation year is just fine, I do copy/paste the header from other files so it would be ideal if there was an automated way to ensure the correct year is used, but it doesnt really matter tbh.

**Comment by UpcraftLP** [comment]
> I think file creation year is just fine, I do copy/paste the header from other files so it would be ideal if there was an automated way to ensure the correct year is used, but it doesnt really matter tbh.

there is! https://github.com/minecrell/Licenser/
(see `Variable substitution in the license header` section)

you just update the template, run the license task again, and it'll update all license headers.

**Comment by i509VCB** [comment]
We already use licenser lol.

**Comment by i509VCB** [comment]
Needs to be updated since this PR has conflicts

**Comment by modmuss50** [comment]
I think we are going to find a better solution to this issue.

**Review by valoeghese — APPROVED** [review]

**Comment by CoolMineman** [comment]
We need a script to change the header based on the last commit.

**Pull request closed without merging**
