### PR TITLE
Load data packs from a general datapacks directory

### PR DESCRIPTION
**Pull request by liach**
@Prospector
https://discordapp.com/channels/507304429255393322/507304429255393324/524024406880813076

### CODE REVIEW

**Comment by asiekierka** [comment]
In my opinion this is extremely out of scope.

**Comment by asiekierka** [comment]
Do they? Is it necessary for *mods*, or just for *modpacks*?

**Comment by liach** [comment]
this is just like the resource packs folder. users do need this so that they don't need to copy their custom stuff into each world every time they create one.

**Comment by Boundarybreaker** [comment]
The original Discord message says someone should make a *mod* to do it. I don't think this is something fit for Fabric main, since it can be done pretty easily without needing to put it in the main API.

**Comment by asiekierka** [comment]
Yes, precisely. This is an user-facing feature, not a modder-facing feature. It does not, as such, belong in the API.

**Comment by liach** [comment]
well, one day people will finally see how important this ability is (e.g. tweaking loot tables when you have blocks or items disabled)

**Comment by liach** [comment]
and this one line does not worth a mod.

**Comment by liach** [comment]
Given its wide usage, should this be included in another mod in the fabric official set of mods, parallel to scala/kotlin support?

**Comment by Boundarybreaker** [comment]
> and this one line does not worth a mod.

this puts a *lot* of faith in Mojang's loading system that isn't exactly founded.

**Comment by liach** [comment]
well, mojang code ain't *that* bad

**Comment by Prospector** [comment]
I don't really see how it would hurt to have this in fabric API. It's not necessary, but it's an easy addition. So I'm on the fence. I think the better idea is allowing directories and zips to load as mods, that way a user could just make a mod without Java files

**Comment by Boundarybreaker** [comment]
>  I think the better idea is allowing directories and zips to load as mods, that way a user could just make a mod without Java files

That'd go to loader, not API. Whichever way you look at it, this isn't something for API to do.

**Comment by liach** [comment]
honestly, the best way is asking mojang for this feature. mojang added data packs for map makers but modders want regular users to utilize data packs.

**Comment by asiekierka** [comment]
It is. Also, this could easily be expanded beyond one line; what if you had a datapacks/ folder, but during world creation you had a menu to choose which datapacks apply? Plus a way for mods to register their own "bundled sample datapacks" for the list. That'd be fantastic IMO.

**Comment by modmuss50** [comment]
I think this should be its own mod, The line has to be drawn somewhere. 

Like @asiekierka said there is quite a lot of other things that could be added around this that would not fit in fabric at all.

By allowing this in it could start a slippery slope of adding extra bloat that isnt needed.

**Comment by Frontrider** [comment]
Make it it's own mod, than we can get our hands on it much faster.

**Comment by Pannoniae** [comment]
I already made it. In theory, it works. In practice, one datapack worked for me which I tested.

**Comment by liach** [comment]
The main thing is default data pack order, extra gui on world creation, and option to copy to the world for distribution.

**Pull request closed without merging**
