### PR TITLE
Fix ItemStack.EMPTY.getItem() rarely returning null due to threading

### PR DESCRIPTION
**Pull request by Technici4n**
See for example https://github.com/AztechMC/Modern-Industrialization/issues/404.

### CODE REVIEW

**Comment by modmuss50** [comment]
Does this happen in vanilla?

**Comment by Technici4n** [comment]
Unclear whether it happens in vanilla or not, but with mods it creates random crashes that don't point to the original modification. Transfer API is also guilty of calling `.setCount(0)` on empty stacks. You'd expect this to be a safe operation, and patching all the call sites is much uglier...
image

As for the performance impact: it seems like the whole injector gets inlined into `updateEmptyState` and the CI allocation is gone... Not too sure as I'm not used to reading hotspot output and had to do some "manual" disassembly, but it looks ok.

**Comment by shartte** [comment]
> Unclear whether it happens in vanilla or not, but with mods it creates random crashes that don't point to the original modification. Transfer API is also guilty of calling `.setCount(0)` on empty stacks. You'd expect this to be a safe operation, and patching all the call sites is much uglier... image
> 
> As for the performance impact: it seems like the whole injector gets inlined into `updateEmptyState` and the CI allocation is gone... Not too sure as I'm not used to reading hotspot output and had to do some "manual" disassembly, but it looks ok.

How did you get the disassembly?

There is a tool that simplifies it greatly but I forgot the details (as usual :-P))

**Comment by Technici4n** [comment]
I used `-XX:+PrintAssembly` which gave this:
image
No decompiler module to directly emit readable assembly, but I copy/pasted the instructions manually into https://defuse.ca/online-x86-assembler.htm. 😅

I also checked the inlining log (with `-XX:+PrintInlining`):
image
which suggests that the method got inlined.

FYI this is what I used to run the tests:
image
image

Not perfect, but seems OK at a glance.

**Comment by liach** [comment]
Does this not hurt other items set to count 0 because they won't return null but a wrong value, which is less severe?

I personally recommend patching the instance field write/reads to local variables or mark the method synchronized for a more comprehensive solution.

**Comment by Technici4n** [comment]
We could overwrite the method to `this.empty = this.item == null || this.item == Items.AIR || this.count <= 0`.

**Comment by Technici4n** [comment]
Changed to an overwrite. Using a cancellable injector because of lithium's mixin: https://github.com/CaffeineMC/lithium-fabric/blob/1.19.x/dev/src/main/java/me/jellysquid/mods/lithium/mixin/item/ItemStackMixin.java that will conflict with any sort of `@Overwrite`.

**Comment by emilyploszaj** [comment]
> Does this happen in vanilla?

For the bug I've reported to mojang, I was able to reproduce this bug in vanilla after several hours, you can see the crash log here. https://bugs.mojang.com/browse/MC-258939

**Comment by modmuss50** [comment]
>  I was able to reproduce this bug in vanilla after several hours

Thats awesome! Thanks 👍

**Review by modmuss50 — APPROVED** [review]

**Comment by Noaaan** [comment]
> > Does this happen in vanilla?
> 
> For the bug I've reported to mojang, I was able to reproduce this bug in vanilla after several hours, you can see the crash log here. https://bugs.mojang.com/browse/MC-258939

Wow. We theorized and joked about this potentially being a vanilla bug. To have it confirmed is another story. Have hunted this issue for over 6 months, so finally putting it to rest is great.
https://github.com/Noaaan/MythicMetals/issues/94

**Comment by emilyploszaj** [comment]
> Wow. We theorized and joked about this potentially being a vanilla bug. To have it confirmed is another story. Have hunted this issue for over 6 months, so finally putting it to rest is great. [Noaaan/MythicMetals#94](https://github.com/Noaaan/MythicMetals/issues/94)

Tech told me he didn't think this was a vanilla bug so I had to prove him wrong

**Pull request merged**
