### PR TITLE
Client gametest threading tweaks

### PR DESCRIPTION
**Pull request by Earthcomputer**
- Fixed cases where the game didn't close properly when a test is thrown or an exception is thrown elsewhere.
- Mutate the stack traces of exceptions thrown in tasks to make them easier to track.

You can review the commits one at a time to make it easier to review.

### CODE REVIEW

**Review by Alexander01998 — COMMENTED** [review]
I've tested this by throwing a `RuntimeException` on each of the threads just after the `in_game_overworld` screenshot. The test thread and client thread worked fine, but the server thread did not, producing this stack trace:

```
[12:29:54] [Test thread/ERROR] (fabric-client-gametest-api-v1) Client gametests failed with an exception
java.lang.NullPointerException: stackTrace[9]
        at java.base/java.lang.Throwable.setStackTrace(Throwable.java:903) ~[?:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.joinAsyncStackTrace(ThreadingImpl.java:261) ~[fabric-client-gametest-api-v1-1.0.0+3dfdebf604-dev.jar:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.runTaskOnOtherThread(ThreadingImpl.java:195) ~[fabric-client-gametest-api-v1-1.0.0+3dfdebf604-dev.jar:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.runOnServer(ThreadingImpl.java:179) ~[fabric-client-gametest-api-v1-1.0.0+3dfdebf604-dev.jar:?]
        at knot/net.fabricmc.fabric.test.client.gametest.ClientGameTestTest.runTest(ClientGameTestTest.java:84) ~[testmodClient/:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.FabricClientGameTestRunner.lambda$start$0(FabricClientGameTestRunner.java:43) ~[fabric-client-gametest-api-v1-1.0.0+3dfdebf604-dev.jar:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.lambda$runTestThread$1(ThreadingImpl.java:129) ~[fabric-client-gametest-api-v1-1.0.0+3dfdebf604-dev.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[12:29:54] [Render thread/ERROR] (FabricLoader) Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NullPointerException: stackTrace[9]
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NullPointerException: stackTrace[9]
        at java.base/java.lang.Throwable.setStackTrace(Throwable.java:903) ~[?:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.joinAsyncStackTrace(ThreadingImpl.java:261) ~[fabric-client-gametest-api-v1-1.0.0+3dfdebf604-dev.jar:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.runTaskOnOtherThread(ThreadingImpl.java:195) ~[fabric-client-gametest-api-v1-1.0.0+3dfdebf604-dev.jar:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.runOnServer(ThreadingImpl.java:179) ~[fabric-client-gametest-api-v1-1.0.0+3dfdebf604-dev.jar:?]
        at knot/net.fabricmc.fabric.test.client.gametest.ClientGameTestTest.runTest(ClientGameTestTest.java:84) ~[testmodClient/:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.FabricClientGameTestRunner.lambda$start$0(FabricClientGameTestRunner.java:43) ~[fabric-client-gametest-api-v1-1.0.0+3dfdebf604-dev.jar:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.lambda$runTestThread$1(ThreadingImpl.java:129) ~[fabric-client-gametest-api-v1-1.0.0+3dfdebf604-dev.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Edit:** To clarify, the correct line number `ClientGameTestTest.java:84` is still in there, but the `NullPointerException` when joining the stack traces doesn't seem right.

Throwing the exception after the `server_in_game` screenshot instead produced a very similar result, so this issue does not seem to be specific to the integrated singleplayer server.

Code to reproduce:

Singleplayer server:
```diff
		{
			enableDebugHud(context);
			waitForWorldTicks(context, 200);
			context.takeScreenshot("in_game_overworld", 0);
+			ThreadingImpl.runOnServer(() -> {
+				throw new RuntimeException("test");
+			});
		}
```

Dedicated server:
```diff
			waitForWorldTicks(context, 20);
			context.takeScreenshot("server_in_game", 0);
+			ThreadingImpl.runOnServer(() -> {
+				throw new RuntimeException("test");
+			});
```

**Comment by Earthcomputer** [comment]
> but the server thread did not, producing this stack trace

try now

**Comment by Alexander01998** [comment]
It works now.

```
[14:12:45] [Test thread/ERROR] (fabric-client-gametest-api-v1) Client gametests failed with an exception
 java.lang.RuntimeException: test
        at knot/net.fabricmc.fabric.test.client.gametest.ClientGameTestTest.lambda$runTest$0(ClientGameTestTest.java:85) ~[testmodClient/:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.runTaskOnThisThread(ThreadingImpl.java:203) ~[fabric-client-gametest-api-v1-1.0.0+db066d5704-dev.jar:?]
        at Async Stack Trace..(Unknown Source) ~[?:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.runTaskOnOtherThread(ThreadingImpl.java:195) ~[fabric-client-gametest-api-v1-1.0.0+db066d5704-dev.jar:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.runOnServer(ThreadingImpl.java:179) ~[fabric-client-gametest-api-v1-1.0.0+db066d5704-dev.jar:?]
        at knot/net.fabricmc.fabric.test.client.gametest.ClientGameTestTest.runTest(ClientGameTestTest.java:84) ~[testmodClient/:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.FabricClientGameTestRunner.lambda$start$0(FabricClientGameTestRunner.java:43) ~[fabric-client-gametest-api-v1-1.0.0+db066d5704-dev.jar:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.lambda$runTestThread$1(ThreadingImpl.java:129) ~[fabric-client-gametest-api-v1-1.0.0+db066d5704-dev.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[14:12:45] [Server thread/INFO] (ServerChunkLifecycleTests) Loaded 3 freshly generated chunks in minecraft:overworld during tick #223
[14:12:45] [Render thread/ERROR] (FabricLoader) Minecraft has crashed!
 net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: test
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.RuntimeException: test
        at knot/net.fabricmc.fabric.test.client.gametest.ClientGameTestTest.lambda$runTest$0(ClientGameTestTest.java:85) ~[testmodClient/:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.runTaskOnThisThread(ThreadingImpl.java:203) ~[fabric-client-gametest-api-v1-1.0.0+db066d5704-dev.jar:?]
        at Async Stack Trace..(Unknown Source) ~[?:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.runTaskOnOtherThread(ThreadingImpl.java:195) ~[fabric-client-gametest-api-v1-1.0.0+db066d5704-dev.jar:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.runOnServer(ThreadingImpl.java:179) ~[fabric-client-gametest-api-v1-1.0.0+db066d5704-dev.jar:?]
        at knot/net.fabricmc.fabric.test.client.gametest.ClientGameTestTest.runTest(ClientGameTestTest.java:84) ~[testmodClient/:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.FabricClientGameTestRunner.lambda$start$0(FabricClientGameTestRunner.java:43) ~[fabric-client-gametest-api-v1-1.0.0+db066d5704-dev.jar:?]
        at knot/net.fabricmc.fabric.impl.client.gametest.ThreadingImpl.lambda$runTestThread$1(ThreadingImpl.java:129) ~[fabric-client-gametest-api-v1-1.0.0+db066d5704-dev.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Review by modmuss50 — APPROVED** [review]
A little bit beyond me, but I trust its working. Makes sense at a high level 👍

**Review by Alexander01998 — APPROVED** [review]
I tried a few other ways to break it, like adding a custom shutdown hook to the testmod and throwing exceptions in other places where they might plausibly happen. Didn't find any issues.

**Pull request merged**
