### PR TITLE
Javadoc fixes

### PR DESCRIPTION
**Pull request by svipthedrunk**
With these fixes "gradle javadoc" should generate without throwing errors.

### CODE REVIEW

**Comment by modmuss50** [comment]
Looks good, would be nice to find a way to get these published to be easily accessible but I think thats out of the scope of this PR.

**Comment by asiekierka** [comment]
The big problem with a javadoc JAR is that we can't remap javadoc JARs, though...

**Comment by asiekierka** [comment]
HMM

What if Loom generated javadoc JARs from remapped sources JARs?

**Comment by svipthedrunk** [comment]
Why should we even supply the docs inside a jar?
Hosting the current  html version somewhere on the internet should be sufficient
If someone wants a local copy of the docs for his local version of the fabric api he can just run the proper gradle/javadoc command

**Comment by grondag** [comment]
Agree it would be nice to have them online.  I post the render-related javadocs [here](https://grondag.github.io/renderosity/fabric-api-javadoc/index.html) and have found them useful on multiple occasions.  (When not at my PC, for example.)

**Comment by grondag** [comment]
Given this is doc only and has three approvals I don’t see a reason to have last call. I don’t want it to get stale/broken from delay. Marked it for merge.

**Pull request merged**
