### PR TITLE
Backport #2901 to 1.18.2

### PR DESCRIPTION
**Pull request by bluebear94**
modmuss50 wanted this to be done at the same time as #3413.

### CODE REVIEW

**Comment by modmuss50** [comment]
Sorry I might not have been that clear, its been a very long time since we have done a 1.18.2 release. Im not too sure if we want to backport this so far?

**Comment by modmuss50** [comment]
@bluebear94 Can you confirm that you have tested this with your mod, and in a mod pack? I just want to be 100% sure its working as intended as I dont plan on doing another 1.18.2 release.

Ill do some basic testing, but it would be nice to know its working for your usecase.

**Comment by bluebear94** [comment]
I’ll test this PR with a patch to the 1.18.2 version of Caxton.

**Comment by bluebear94** [comment]
@modmuss50, here’s a screenshot of Caxton modified to use the PRed core shader API running with the AOF Skylore pack on 1.18.2. I’ve also published the [branch for this build](https://gitlab.com/Kyarei/caxton/-/tree/mf/use-api-shader-events-1.18.2).

**Comment by modmuss50** [comment]
> @modmuss50, here’s a screenshot of Caxton modified to use the PRed core shader API running with the AOF Skylore pack on 1.18.2. I’ve also published the [branch for this build](https://gitlab.com/Kyarei/caxton/-/tree/mf/use-api-shader-events-1.18.2).
> 
> 

Many thanks for that, I think ill aim to get this out over the weekend. Its going to take me a few hours to sit with the all the builds I need to do 😩

**Review by modmuss50 — APPROVED** [review]

**Pull request merged**
