### PR TITLE
Add script to only enable a subset of projects for development

### PR DESCRIPTION
**Pull request by modmuss50**
This should help those who struggle to build FAPI on their computers, it allows you to "focus" on specific modules.

Run `java gradle/Focus.java fabric-networking-api-v1` to focus on fabric-networking-api-v1 and its dependencies.

Is this something people would find useful to have?

### CODE REVIEW

**Comment by apple502j** [comment]
Not sure if this is useful for me (I just `runTestmodClient` on module directly), but seems good.

**Comment by modmuss50** [comment]
> Not sure if this is useful for me (I just `runTestmodClient` on module directly), but seems good.

It might help you use an IDE, as this will only load the modules you care about in the IDE, I would strongly reccomend using the IDE run configs, while using intelij to build. Ill only merge this if someone is actually going to use it, otherwise its kinda pointless.

**Comment by modmuss50** [comment]
Going to merge this, easy enough to remove if no one ends up using it.

**Comment by embeddedt** [comment]
Very late, but this will definitely come in handy for me at some point, thank you!

**Pull request merged**
