### PR TITLE
[1.15.2] Container factory exists method.

### PR DESCRIPTION
**Pull request by ghost**
Adds a single method to `fabric-containers-v0` which allows modders to check if a container factory with a given identifier has already been registered.

Reasoning behind this PR is that I would like to implement a config for my mod to specify which screen / container factory is used and would like to be able to tell the user if they have picked an unsupported value.

This won't be needed for the new screen handler updated version of this module as the screen handlers are registered to a minecraft registry instead of a private map.

If there are any issues with checkstyle ( I have ran it locally ) or with the version number please let me know.

### CODE REVIEW

**Review by i509VCB — APPROVED** [review]
Looks like a nice little addition. Might not get much use in screenhandlers v1 since we moved to screen handler type, but this is a different type of api than that.

**Review by LemmaEOF — APPROVED** [review]

**Review by Prospector — APPROVED** [review]

**Review by shedaniel — APPROVED** [review]

**Review by Player3324 — APPROVED** [review]

**Comment by ghost** [comment]
Nevermind, it's clear this isn't getting merged.

**Comment by i509VCB** [comment]
You made no real effort after the initial reviews (got past player even) to tell modmuss to review or poke an admin to tell him to review.

**Comment by liach** [comment]
Fyi we've moved away from containers to screen handler

**Comment by ghost** [comment]
Yeah I know hence why I targeted 1.15.2, but I'm no longer supporting that anyways.

**Pull request closed without merging**
