### PR TITLE
Biomemodifications: Check to make sure Feature isn't present before adding it

### PR DESCRIPTION
**Pull request by JT122406**
Fixes an issue where a feature order cycle error will happen because a feature may be added to a biome twice.  This can occur if a biome appears in more than one tag and you want a feature in biomes from both tags, currently it gets added twice to the biome causing a feature order cycle error

### CODE REVIEW

**Comment by apple502j** [comment]
Maybe a log?

**Comment by JT122406** [comment]
Like print it to the console log that this is happening?

**Comment by JT122406** [comment]
Thinking maybe a debug or a warn or? In my head putting it in like info doesn't make sense as this could happen very easily with tags and it's not like a "bad" thing it's just something that happens

**Comment by modmuss50** [comment]
I think this seems fine, as it can happen in a valid case. We would only tend to log if something was broken.

**Review by modmuss50 — APPROVED** [review]

**Comment by JT122406** [comment]
I wanna get this back ported to 1.21.1 how do yall handle that do I need to make a pr into that version?

**Pull request merged**
