### PR TITLE
Update loom

### PR DESCRIPTION
**Pull request by modmuss50**
This should be a lot faster. 

Needs a little bit more testing before id by happy using it to build. This will allow the use of the jetbrains annotations as well. (Out of scope for this PR)

### CODE REVIEW

**Comment by i509VCB** [comment]
Don't we need to swap JSR compileOnly dep (in game rules) to jetbrains or is jetbrains auto included and we just need to drop JSR there.

**Comment by modmuss50** [comment]
Good call, all refrences to JSR should be gone with this. Will update the PR

**Review by Player3324 — APPROVED** [review]

**Review by i509VCB — APPROVED** [review]

**Comment by modmuss50** [comment]
Don't merge just yet, this is apparenly still broken as its crashing in prod.

**Comment by modmuss50** [comment]
This seems to now be working correctally. After merging you may need to run with `--refresh-dependencies` once locally.

**Pull request merged**
