### PR TITLE
add armor texture provider hook

### PR DESCRIPTION
**Pull request by asiekierka**
TODO:

* Better interface name?
* Is capturing ItemStack here useful for modders? Do modders realistically vary their armor textures by NBT at any point, often enough to not justify mixing deeper into ArmorFeatureRenderer with a custom renderer? Would simplify the patch not to.

### CODE REVIEW

**Comment by Boundarybreaker** [comment]
`NamespacedArmorItem` fits the guidelines more, since Namespaced is an adjective. I can also see an advantage to NBT for anything dyeable.

**Comment by asiekierka** [comment]
No, that's the *texture*. Dyes are handled separately.

**Comment by Boundarybreaker** [comment]
Ah, right, that was just changed. I can see advantages to having NBT access for stuff like IC2's jetpack duct tape, but since that's supposed to be for *any* armor that'd be better done as a mixin.

**Comment by asiekierka** [comment]
From discussion on IRC:

* This hook may be best left to just ArmorItem,
* because Mojang generally implements custom renderers via appending them in .addFeature(). For this, an event should be provided (no performance issue - runs only on instantiation).

**Comment by asiekierka** [comment]
Time to make a new PR.

**Pull request closed without merging**
