### PR TITLE
Make FabricToolTags Identified tags

### PR DESCRIPTION
**Pull request by Shnupbups**
Allows for using them in datagen without annoying casting

### CODE REVIEW

**Comment by Juuxel** [comment]
This is sadly a breaking change, though I'd be glad to have this.

**Comment by Shnupbups** [comment]
> This is sadly a breaking change, though I'd be glad to have this.

How would this be a breaking change? `Tag.Identified` extends `Tag`, so everything should work just fine? I'm probably missing something obvious though, I am operating on little sleep

**Comment by Shnupbups** [comment]
I mean I can always keep the original `FabricToolTags` class, deprecate it, and make a new one that uses Identified tags? maybe in the mining level api instead of tool attribute api?

**Comment by BasiqueEvangelist** [comment]
> > This is sadly a breaking change, though I'd be glad to have this.
> 
> How would this be a breaking change? `Tag.Identified` extends `Tag`, so everything should work just fine? I'm probably missing something obvious though, I am operating on little sleep

This would break binary compatibility, since the descriptors of the fields changed (`Tag` -> `Tag.Identified`)

**Comment by Juuxel** [comment]
> I mean I can always keep the original FabricToolTags class, deprecate it, and make a new one that uses Identified tags?

I don't think we need a fourth copy of this class in FAPI. And yeah, changing the field descriptor from `Tag` to `Tag$Identified` breaks binary compat.

**Comment by warjort** [comment]
Why not just duplicate the field?

````
// New field with new type
+public static final Tag.Identified<Item> AXES_TAG = register("axes");

// Old field name with old descriptor (just an alias)
public static final Tag<Item> AXES = AXES_TAG;
````

**Comment by deirn** [comment]
What about adding a method in `FabricTagBuilder` that cast it to `Identified`?

**Comment by Shnupbups** [comment]
> What about adding a method in `FabricTagBuilder` that cast it to `Identified`?

At that point you may as well just cast it yourself; `FabricToolTags.identified(FabricToolTags.PICKAXES)` looks just as bad as `(Tag.Identified<Item>) FabricToolTags.PICKAXES`.

For now I think I'll go with what warjort said and just duplicate the field, marking the old ones as deprecated. Only small issue with that is that a not-so-ideal naming scheme has to be used for the new ones in order to keep the old ones.

**Comment by deirn** [comment]
No, not in `FabricToolTags` but in `FabricTagBuilder`, the datagen builder. Any tag from `TagFactory` and `TagRegistry` is already `Identified` anyway. Vanilla static tags too.

**Comment by Shnupbups** [comment]
> No, not in `FabricToolTags` but in `FabricTagBuilder`, the datagen builder. Any tag from `TagFactory` and `TagRegistry` is already `Identified` anyway. Vanilla static tags too.

Ah, right, misread, sorry. That sounds much better! Will do.

**Comment by Shnupbups** [comment]
well in that case i'm gonna close this and add the changes to #1889 (which I'm also probably going to split into two PRs, one for the renames and one for the additions)

**Pull request closed without merging**
