### PR TITLE
Move test mods into their own modules

### PR DESCRIPTION
**Pull request by modmuss50**
This is based of work from #251 and the suggestion from @Pyrofab 

Im sure ive made some mistakes and I didnt take a lot of care in naming/testing things.

### CODE REVIEW

**Comment by Sollace** [comment]
If someone can look over these and check that the test mods work (include everything needed to run them in the repo) I'd gladly rebase my PR on this when it's merged.

**Comment by valoeghese** [comment]
This pr hasn't had any progress since august lol

**Comment by Draylar** [comment]
Valo, one discussion we had was about restarting with blank testmods so we can focus on making the examples as thorough as possible (as opposed to porting old tests). I made a working testmods module today, but I still need to adapt it so tests are per-module rather than in a single module. I may be able to get something out in the next week or so.

**Comment by i509VCB** [comment]
I honestly feel we should deal with this test migration by migrating everything that currently works, and in future PRs migrate the broken tests.

**Comment by modmuss50** [comment]
I will be re-creating a PR for this

**Pull request closed without merging**
