### PR TITLE
allow key bindings to be unregistered

### LINKED ISSUE #1026: unregister key bindings
allow registered key bindings to be unregistered

### PR DESCRIPTION
**Pull request by nnym**
allow key bindings to be registered and checking whether they are registered and close #1026

### CODE REVIEW

**Comment by nnym** [comment]
concern

**Comment by modmuss50** [comment]
Whats the usecase for this? Could you just not register the keybindings?

**Comment by nnym** [comment]
Only 1 of a set of conflicting key bindings can be activated. This would allow optional key bindings that do not conflict unless explicitly enabled by the player while retaining default and custom values. They could be toggled dynamically without having to rebind them each time or having to restart to prevent them from being registered after changing settings that disable them.

**Comment by i509VCB** [comment]
I really don't think this is the proper approach.

One solution may be a sort of `KeyBindingConflictHandler` you can assign to a keybind through a sort of builder.

**Comment by i509VCB** [comment]
I don't believe this is a good solution to the problem.

Closing also since there has been no response for a while

**Pull request closed without merging**
