### PR TITLE
Add all languages ​​Spanish

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by frqnny — COMMENTED** [review]
Doesn't Spanish default to es_es if the others don't exist? We don't have a british english variant because it goes to en_us. 
I don't think you need all those Spanish files but I'm not 100% sure.

**Comment by Technici4n** [comment]
> Doesn't Spanish default to es_es if the others don't exist?

I just tested and there is no fallback mechanism between say fr_fr and fr_ca.

> We don't have a british english variant because it goes to en_us.

That's because it always goes to en_us if there is no translation. :wink:

**Review by Technici4n — APPROVED** [review]

**Review by frqnny — APPROVED** [review]

**Review by modmuss50 — APPROVED** [review]

**Comment by Technici4n** [comment]
@modmuss50 Should maybe change the base branch? (Or merge manually)

**Comment by modmuss50** [comment]
I'll merge this manually 👍

**Comment by modmuss50** [comment]
Manually squished and merged into 1.20.1: https://github.com/FabricMC/fabric/commit/2825407a16affcc0d1649d676dec35d8a6c91056

Thanks :)

**Pull request closed without merging**
