### PR TITLE
Fix ForwardingBakedModel not forwarding isSideLit. Closes #501

### LINKED ISSUE #501: ForwardingBakedModel does not forward isSideLit
There's not really much to say. It just doesn't, and it probably should.

### PR DESCRIPTION
**Pull request by modmuss50**

### CODE REVIEW

**Comment by modmuss50** [comment]
Will need to be pulled into both 1.15 and 1.16.

**Review by Player3324 — APPROVED** [review]

**Comment by Player3324** [comment]
I think that's fine, not 100% sure about the change in DamageModel though.

**Review by grondag — CHANGES_REQUESTED** [review]
DamageModel extends ForwardingBakedModel, so this makes sense in terms of the class hierarchy, but  DamageModel is no longer required in 1.15 and can be removed.  Damage is handled in 1.15 via multi-texturing instead of repainting the base model each frame.

**Comment by liach** [comment]
Right, in modern b3d damage is an overlay render layer

**Comment by modmuss50** [comment]
Updated to also remove DamageModel

**Pull request merged**
